# A dot in front of a job disables the job

workflow: # run pipeline only if one condition is true:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # commit to default branch (master)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # pipeline started from a merge request
    - if: $CI_PIPELINE_SOURCE == "web" # pipelines created by selecting 'Run pipeline'

variables: # "declaration" neccessary for use in job definitions
  MPI: $MPI
  OMP: $OMP
  COMPILER: $COMPILER

default:
  before_script:
    - cd src
    - if [ $COMPILER == 'COMPILER=INTEL' ]; then module load mpi compiler ;fi
    - if [ $COMPILER == 'COMPILER=INTEL' ]; then ifort --version; mpiifort --version; else gfortran --version; mpif90 --version ;fi
    - if [ $MPI == 'MPI=1' ]; then mpirun --version; fi
    - if [ $COMPILER == 'COMPILER=INTEL' ]; then sed 's!mpif90!mpiifort!g' makefiles/INTEL.mk -i; fi
  after_script:
    - if [ $COMPILER == 'COMPILER=INTEL' ]; then module unload mpi/2021.6.0 compiler/2022.1.0 ;fi

stages:
  - build
  - flags
  - version
  - test

.standardJob:
  only: # defines when the job(s) run(s)
    - branches
    - merge_requests
    - web # pipelines created by selecting 'Run pipeline'

Check Version:
  stage: version
  before_script: [] # do not run default before_script
  script:
    - chmod +x test/checkVersionUpdate.sh
    - ./test/checkVersionUpdate.sh
  rules:
    # allow failure for direct commit to default branch (master)
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
      allow_failure: false

GNU:
  extends: .standardJob
  stage: build
  script:
    - make all -j 3 COMPILER=GNU $MPI $OMP
  parallel:
    matrix: # run job for each parameter combination
      - MPI: [MPI=1, MPI=0]
        OMP: [OMP=0, OMP=1]

INTEL:
  extends: .standardJob
  variables:
    COMPILER: COMPILER=INTEL
  stage: build
  script:
    - make all -j 3 COMPILER=INTEL $MPI $OMP
  parallel:
    matrix:
      - MPI: [MPI=1, MPI=0]
        OMP: [OMP=0, OMP=1]
  retry: 2

TRANS:
  extends: .standardJob
  stage: flags
  script:
    - make all -j 3 $COMPILER $MPI $OMP TRANS=1
  parallel:
    matrix:
      - COMPILER: [COMPILER=GNU, COMPILER=INTEL]
        MPI: [MPI=1, MPI=0]
        OMP: [OMP=1, OMP=0]
  retry: 2

MPIF08:
  extends: .standardJob
  variables:
    MPI: MPI=1
  stage: flags
  script:
    - make all -j 3 $COMPILER MPI=$MPI $OMP TRANS=$TRANS MPI_USE_MODULE=$MPI_USE_MODULE
  parallel:
    matrix:
      - COMPILER: [COMPILER=GNU, COMPILER=INTEL]
        OMP: [OMP=1, OMP=0]
        TRANS: [TRANS=1, TRANS=0]
        MPI_USE_MODULE: [MPI_USE_MODULE=1, MPI_USE_MODULE=0]
  retry: 2

HBOND:
  extends: .standardJob
  stage: flags
  script:
    - make all -j 3 $COMPILER $MPI HBOND=1
  parallel:
    matrix:
      - COMPILER: [COMPILER=GNU, COMPILER=INTEL]
        MPI: [MPI=1, MPI=0]
  retry: 2

OSMOP:
  extends: .standardJob
  stage: flags
  script:
    - make all -j 3 $COMPILER $MPI $OSMOP
  parallel:
    matrix:
      - COMPILER: [COMPILER=GNU, COMPILER=INTEL]
        MPI: [MPI=1, MPI=0]
        OSMOP: [OSMOP=1, OSMOP=2]
  retry: 2

SPME:
  extends: .standardJob
  stage: flags
  script:
    - make all -j 3 $COMPILER $MPI SPME=1
  parallel:
    matrix:
      - COMPILER: [COMPILER=GNU, COMPILER=INTEL]
        MPI: [MPI=1, MPI=0]
  retry: 2

GNU DEBUG:
  extends: .standardJob
  stage: build
  script:
    - make all COMPILER=GNU TARGET=DEBUG

GNU MPI SP:
  extends: .standardJob
  stage: build
  script:
    - make all -j 3 COMPILER=GNU MPI=1 SP=1

test:
  extends: .standardJob
  before_script: [] # do not run default before_script
  script:
    - echo Test..
