/*
 * changeMaxCutoffJFrame.java
 *
 * Created on 2. Februar 2010, 15:21
 */

package ms_newpars;

//import java.awt.Desktop.Action;

import javax.swing.JTextField;


/**
 *
 * @author  kdiffo
 */
public class changeMaxCutoffJFrame extends javax.swing.JFrame {

    /** Creates new form changeMaxCutoffJFrame
     * @param parent1
     * @param parent2
     * @param parent3 */
    public changeMaxCutoffJFrame(Ensemble parent1, EnsemblePanel parent2, FileGenGUI parent3 ) {
        //super(parent3);
        this.main1 = parent1;
        this.main2 = parent2;
        this.main3 = parent3;
        initComponents();
        

        this.messageLabel.setText("For Ensembles other than NVT, NVE");
        this.maxCutoffValue.setText(String.valueOf(this.main1.getCutOff()));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Max Cutoff");
    }
    
    private double newCutoffCalc(double val1, double val2) {
            double val3 = val1 - val2;
            return val3;
        }
    

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cutoffReductTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        maxCutoffValue = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("change max Cutoff");

        jLabel1.setText("Max Cutoff:");

        jLabel3.setText("Cutoff Reduction of:");

        cutoffReductTextField.setText("0.01");
        cutoffReductTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffReductTextFieldFocusLost(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton(evt);
            }
        });

        maxCutoffValue.setText("jLabel2");

        messageLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxCutoffValue)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(okButton)
                        .addComponent(cutoffReductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maxCutoffValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cutoffReductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FocusGained
        // TODO add your handling code here:
            JTextField jtf = (JTextField) evt.getSource();
            jtf.selectAll();
}//GEN-LAST:event_FocusGained

    private void okButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton
        // TODO add your handling code here:
        //this.Co = newCutoffCalc(this.Co,this.Diff);
        this.Diff = Double.parseDouble(this.cutoffReductTextField.getText());         
        this.Co = newCutoffCalc(this.main1.getCutOff(),this.Diff);
        this.Co = Math.round(this.Co*10000.)/10000. ;
        
        this.main1.setCutOff(this.Co);
        this.main1.setCutOffLJ(this.Co);
            this.main1.setCutOffDQ(this.Co);
            this.main1.setCutOffQQ(this.Co);
            this.main1.setCutOffDD(this.Co);
        if (this.main3.cutofftypeComboBox.getSelectedItem().toString().equals("COM")){    
            
            this.main2.jLabel24.setEnabled(true);
            this.main2.cutoffTextField.setEnabled(true);
            this.main2.cutoffTextField.setText(String.valueOf(this.main1.getCutOff())); 
        }else{
            
            this.main2.jLabel24.setEnabled(true);
            this.main2.cutoffTextField.setEnabled(false);
           
            this.main2.cutoffljTextField.setText(String.valueOf(this.main1.getCutOffLJ()));
            this.main2.cutoffdqTextField.setText(String.valueOf(this.main1.getCutOffDQ()));
            this.main2.cutoffqqTextField.setText(String.valueOf(this.main1.getCutOffQQ()));
            this.main2.cutoffddTextField.setText(String.valueOf(this.main1.getCutOffDD()));
        }
        this.dispose();
    }//GEN-LAST:event_okButton

    private void cutoffReductTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffReductTextFieldFocusLost
        // TODO add your handling code here:
        this.cutoffReductTextField.setText(String.valueOf(this.cutoffReductTextField.getText()));
        //this.Diff = Double.valueOf(this.cutoffReductTextField.getText()).doubleValue(); 
        // double val = this.main1.getCutOff();
       
        
        // this.newCutoffTextField.setText(String.valueOf(this.Co));  

        // val = this.Co;
       

    }//GEN-LAST:event_cutoffReductTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cutoffReductTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maxCutoffValue;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables


    private double Co ;
    private double Diff= 0.01;
 
    private Ensemble main1;
    private EnsemblePanel main2;
    private FileGenGUI main3;

}
