/*
 * ChemPotMethodJFrame.java
 *
 * Created on 2. Mai 2007, 16:37
 */

package ms_newpars;


import java.io.*;

//import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextArea;

/**
 *
 * @author  berreth
 */
public class ChemPotMethodJFrame extends javax.swing.JFrame {
    
    /** Creates new form ChemPotMethodJFrame
     * @param curPm */
    public ChemPotMethodJFrame(PotentialModel curPm) {
        initComponents();
        this.weightFactorsTextField.setVisible(false);
        this.jScrollPane1.setVisible(false);
        this.thermoIntpanel.setVisible(false);
        
        this.pm = curPm;
        this.potModelName.setText(this.pm.getName());
        this.chemPotMethodTypeComboBox.setSelectedItem(this.pm.getChemPotMethod());
        this.nTestTextField.setText(String.valueOf(this.pm.getNTest()));
        this.weightFactorsType.setSelectedItem(this.pm.getWeightFactorsType());
        this.weightFactorsTextField.setText(this.pm.getWeightFactors());
        
        this.lbmin_txt.setText(String.valueOf(this.pm.getlambdamin()));
        this.lbmax_txt1.setText(String.valueOf(this.pm.getlambdamax()));
        this.nbins_txt.setText(String.valueOf(this.pm.getnbins()));
        this.lbstepmax_txt.setText(String.valueOf(this.pm.getlambdastepmax()));
        this.lbexp_txt.setText(String.valueOf(this.pm.getlambdaexp()));
    }
    
    /**
     * Validation of integer value
     * 
     * @param str Input
     * 
     * @return Validated integer
     */
    public int validateInputInt(String str){
        int ret = 0;
        if (str.length() > 0) {
            try {
                ret = Integer.parseInt(str);
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid number.");
            }
        }
        
        return ret;
    }
    
    /**
     * Validation of double value
     * 
     * @param str Input
     * 
     * @return Validated double
     */
    public double validateInputDouble(String str)
    {
        double ret = 0.0;
        if (str.length() > 0) {
            try {
                ret = Double.parseDouble(str);
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid number.");
            }
        }
        
        return ret;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        potModelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chemPotMethodTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nTestTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weightFactorsTextField = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        weightFactorsType = new javax.swing.JComboBox();
        thermoIntpanel = new javax.swing.JPanel();
        llbmin_lbl = new javax.swing.JLabel();
        lbmin_txt = new javax.swing.JTextField();
        llbstepmax_lbl = new javax.swing.JLabel();
        lbstepmax_txt = new javax.swing.JTextField();
        lbexp_txt = new javax.swing.JTextField();
        llbexp_lbl = new javax.swing.JLabel();
        lbmax_txt1 = new javax.swing.JTextField();
        llbmax_lbl = new javax.swing.JLabel();
        nbins_lbl = new javax.swing.JLabel();
        nbins_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chemical Potential Method");

        jLabel1.setText("for Potential Model:");

        potModelName.setText("pmLabel");

        jLabel2.setText("Chemical Potential Method");

        chemPotMethodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Widom", "ThermoInt", "GradIns" }));
        chemPotMethodTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemPotMethodTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("nTest");
        jLabel3.setEnabled(false);

        nTestTextField.setText("0");
        nTestTextField.setEnabled(false);

        jLabel4.setText("WeightFactors");
        jLabel4.setEnabled(false);

        weightFactorsTextField.setColumns(20);
        weightFactorsTextField.setRows(5);
        jScrollPane1.setViewportView(weightFactorsTextField);

        closeButton.setText("save");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        weightFactorsType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guess", "OptSet" }));
        weightFactorsType.setEnabled(false);
        weightFactorsType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightFactorsTypeActionPerformed(evt);
            }
        });

        llbmin_lbl.setText("LambdaMin");

        lbmin_txt.setText("0.2");

        llbstepmax_lbl.setText("LambdaStepMax");

        lbstepmax_txt.setText("0.1");

        lbexp_txt.setText("4");

        llbexp_lbl.setText("LambdaExponent");

        lbmax_txt1.setText("1.0");

        llbmax_lbl.setText("LambdaMax");

        nbins_lbl.setText("NBins");

        nbins_txt.setText("100");

        org.jdesktop.layout.GroupLayout thermoIntpanelLayout = new org.jdesktop.layout.GroupLayout(thermoIntpanel);
        thermoIntpanel.setLayout(thermoIntpanelLayout);
        thermoIntpanelLayout.setHorizontalGroup(
            thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, thermoIntpanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(llbmax_lbl)
                    .add(nbins_lbl)
                    .add(llbmin_lbl))
                .add(19, 19, 19)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(lbmin_txt)
                    .add(lbmax_txt1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .add(nbins_txt))
                .add(25, 25, 25)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(llbstepmax_lbl)
                    .add(llbexp_lbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lbstepmax_txt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .add(lbexp_txt))
                .addContainerGap())
        );
        thermoIntpanelLayout.setVerticalGroup(
            thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thermoIntpanelLayout.createSequentialGroup()
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(llbmin_lbl)
                    .add(lbmin_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbstepmax_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(llbstepmax_lbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(llbmax_lbl)
                    .add(lbmax_txt1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(llbexp_lbl)
                    .add(lbexp_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(thermoIntpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(nbins_lbl)
                    .add(nbins_txt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(potModelName))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(chemPotMethodTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(weightFactorsType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(closeButton))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nTestTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, thermoIntpanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(potModelName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(chemPotMethodTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nTestTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(thermoIntpanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(weightFactorsType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @see ChemPotMethodJFrame#textFieldVisible()
     * 
     * @param evt 
     */
    private void weightFactorsTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFactorsTypeActionPerformed
        textFieldVisible();
    }//GEN-LAST:event_weightFactorsTypeActionPerformed
    
    /**
     * Before closing saves all the data into Potential Model object
     * 
     * @param evt 
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.pm.setChemPotMethod(this.chemPotMethodTypeComboBox.getSelectedItem().toString());
        this.pm.setNTest(this.validateInputInt(this.nTestTextField.getText()));
        this.pm.setlambdamin(this.validateInputDouble(this.lbmin_txt.getText()));
        this.pm.setlambdamax(this.validateInputDouble(this.lbmax_txt1.getText()));
        this.pm.setnbins(this.validateInputInt(this.nbins_txt.getText()));
        this.pm.setlabdastepmax(this.validateInputDouble(this.lbstepmax_txt.getText()));
        this.pm.setlambdaexp(this.validateInputInt(this.lbexp_txt.getText()));
        this.pm.setWeightFactorsType(this.weightFactorsType.getSelectedItem().toString());
        this.pm.setWeightFactors(this.weightFactorsTextField.getText().trim());
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /**
     * Enable or disable UI controls according to the specified case
     * 
     * @param evt 
     */
    private void chemPotMethodTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemPotMethodTypeComboBoxActionPerformed
        if(this.chemPotMethodTypeComboBox.getSelectedItem().equals("GradIns")){
            this.jLabel3.setVisible(false);
            this.nTestTextField.setVisible(false);
            this.thermoIntpanel.setVisible(false);
            this.jLabel4.setVisible(true);
            this.jLabel4.setEnabled(true);
            this.weightFactorsType.setVisible(true);
            this.weightFactorsType.setEnabled(true);        
            textFieldVisible(); 
        } else if (this.chemPotMethodTypeComboBox.getSelectedItem().equals("Widom")) {
            this.jLabel3.setVisible(true);
            this.jLabel3.setEnabled(true);
            this.nTestTextField.setVisible(true);
            this.nTestTextField.setEnabled(true);
            this.jLabel4.setVisible(false);
            this.weightFactorsType.setVisible(false);
            this.thermoIntpanel.setVisible(false);
            textFieldVisible();
        } else if (this.chemPotMethodTypeComboBox.getSelectedItem().equals("ThermoInt")) {
            this.thermoIntpanel.setVisible(true);
            this.jLabel3.setVisible(false);
            this.nTestTextField.setVisible(false);
            this.jLabel4.setVisible(false);
            this.weightFactorsType.setVisible(false);
        }
        else {
            this.thermoIntpanel.setVisible(false);
            this.jLabel3.setVisible(false);
            this.nTestTextField.setVisible(false);
            this.jLabel4.setVisible(false);
            this.weightFactorsType.setVisible(false);
            textFieldVisible();    
        }
    }//GEN-LAST:event_chemPotMethodTypeComboBoxActionPerformed

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
            JTextField jtf = (JTextField) evt.getSource();
            jtf.selectAll();
}//GEN-LAST:event_focusGained

    private void focusGainedArea(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedArea
            JTextArea jtf = (JTextArea) evt.getSource();
            jtf.selectAll();
    }//GEN-LAST:event_focusGainedArea
    
    /**
     * Set the weight factor value according to the NFluct value from the file.
     * 
     */
    private void textFieldVisible(){
        if ( (this.weightFactorsType.getSelectedItem().equals("Guess") || this.weightFactorsType.getSelectedItem().equals("OptSet")) && this.chemPotMethodTypeComboBox.getSelectedItem().equals("GradIns")){
            this.weightFactorsTextField.setVisible(true);
            this.weightFactorsTextField.setEnabled(true);
            this.jScrollPane1.setVisible(true);
            
            
            int NFluct = readNFluct(this.pm.getFile());
            
            if (NFluct != 0){
                int n = 0;
                int factor = 1;
                this.weightFactorsTextField.setText("");
                do{                    
                    if (n == 1){
                        factor = 4;
                    }
                    else if (n == 2){                        
                        factor = 16;
                    }
                    else if (n == 3){
                        factor = 20;
                    }
                    else if (n > 3){
                        factor = factor + 20;
                    }else {}   
                
                    String str = String.valueOf(factor);
                    this.weightFactorsTextField.append(str + "\n");
                
                    n++;
                
                }while (n < NFluct); 
            }   
        }else {
            
            this.weightFactorsTextField.setVisible(true);
            this.weightFactorsTextField.setEnabled(false);
            this.jScrollPane1.setVisible(true);
        } 
    }
    
    /**
     * Read NFluct value from the file specified.
     * 
     * @see ChemPotMethodJFrame#textFieldVisible()
     * 
     * @param pmFile Path of the file
     * 
     * @return Value of NFluct
     */
   private int readNFluct(File pmFile){

        String adr = pmFile.getPath();
        int NFluct = 0;

        try {
            FileInputStream fis = new FileInputStream(adr);
            BufferedReader buff = new BufferedReader (new InputStreamReader(fis));
            try{
                String line;
                String[] words;
                while ((line = buff.readLine()) != null){
                    if (line.indexOf("NFluct") != -1){
                        words = line.split("=");
                        words[0] = treatment(words[0]);
                        if(words[0].equals("NFluct")){
                            words[1]= treatment(words[1]);
                            if (!words[1].equals("0")){
                                
                                NFluct = Integer.parseInt(words[1]);
                            }else{
                                JOptionPane.showMessageDialog(new JFrame(), "Token error or \n No given Value of NFluct");
                            }
                        }else{
                            JOptionPane.showMessageDialog(new JFrame(), "Token error when writting NFluct in pmFile"); 
                        }
                    }
                }
                if (NFluct == 0){
                    JOptionPane.showMessageDialog(new JFrame(), "Change molecule \n No fluctuating states defined for this molecule");
                }  
            } finally{
                buff.close();               
            }
        }catch(IOException ioe){
            JOptionPane.showMessageDialog(new JFrame(), "Error--" + ioe.toString());
        }  
        return NFluct;
    }
   
   /**
    * Retrieve the vale from specified string.
    * 
    * @see ChemPotMethodJFrame#readNFluct(java.io.File)
    * 
    * @param str String of values
    * 
    * @return Value
    */
   private String treatment(String str){
       StringTokenizer stk = new StringTokenizer(str, " ");
       String str1 = new String();
       while(stk.hasMoreTokens()){
           str = String.valueOf(stk.nextToken());
           if (!str.equals(" ")){
               str1 = str;
               if(str1.charAt(0) == ' '|| str1.charAt(0)=='\t')
                   str1 = "0";           
           }else{
               str1 = "0";
           }
       }
       
       return str1;
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox chemPotMethodTypeComboBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbexp_txt;
    private javax.swing.JTextField lbmax_txt1;
    private javax.swing.JTextField lbmin_txt;
    private javax.swing.JTextField lbstepmax_txt;
    private javax.swing.JLabel llbexp_lbl;
    private javax.swing.JLabel llbmax_lbl;
    private javax.swing.JLabel llbmin_lbl;
    private javax.swing.JLabel llbstepmax_lbl;
    private javax.swing.JTextField nTestTextField;
    private javax.swing.JLabel nbins_lbl;
    private javax.swing.JTextField nbins_txt;
    private javax.swing.JLabel potModelName;
    private javax.swing.JPanel thermoIntpanel;
    private javax.swing.JTextArea weightFactorsTextField;
    private javax.swing.JComboBox weightFactorsType;
    // End of variables declaration//GEN-END:variables
    private PotentialModel pm;

    //private Ensemble eData;
}
