/*
 * EnsemblePanel.java
 *
 * Created on 4. November 2006, 15:29
 */

package ms_newpars;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.*;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;


/**
 *
 * @author  Christian Berreth
 * 
 * This class provides another interface for the Ensemble data.
 * 
 */
public class EnsemblePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form EnsemblePanel
     */
    List<JComboBox> Jbox = new ArrayList<JComboBox>();
    EachRowEditor rowEditor;

    /**
     * Creates new Ensemble panel
     * @param parent
     */
    public EnsemblePanel(FileGenGUI parent) {
        initComponents();
        eData = new Ensemble();
        this.main = parent;
        
        this.eData.potModelList = new LinkedList<PotentialModel>();
        this.eData.Commentsdata = new ArrayList<String>();
        this.helpMap = parent.helpMap;
        settooltipforlabels();
        updateEnsemblePanel();
        try {
            rowEditor = new EachRowEditor(this.potmodelTable);
        } catch (Exception ex) {
            System.out.println(ex.getStackTrace());
        }
        
    }
    /**
     * Add drop down into the Potential model table.
     */
    private void addcomboToPotModelTable(){
        int row = this.potmodelTable.getRowCount() - 1;
        Jbox.add(new JComboBox(new String[]{"Yes","No"}));
            rowEditor.setEditorAt(row, new DefaultCellEditor(Jbox.get(Jbox.size() - 1)));
    }
    
    /**
     * From the helpMap data structures it adds tool tips into UI controls.
     */
    private void settooltipforlabels()
    {
        for(Component cm: ensemblePanel.getComponents())
        {
            if(cm instanceof JLabel)
            {
                JLabel lbl = (JLabel) cm;
                if(helpMap.containsKey(lbl.getText().toLowerCase())) {
                String tooltip = this.main.addLinebreaks(helpMap.get(lbl.getText().toLowerCase()),30);
                lbl.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
                }
            }
            else
            if(cm instanceof JButton)
            {
                JButton btn = (JButton) cm;
                if(helpMap.containsKey(btn.getText().toLowerCase())) {
                String tooltip = this.main.addLinebreaks(helpMap.get(btn.getText().toLowerCase()),30);
                btn.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
                }
            }
            else
                if(cm instanceof JPanel)
                {
                    JPanel jp = (JPanel) cm;
                    for(Component cmp: jp.getComponents())
                    {
                        if(cmp instanceof JLabel)
                        {
                            JLabel lbl = (JLabel) cmp;
                            if(helpMap.containsKey(lbl.getText().toLowerCase())) {
                            String tooltip = this.main.addLinebreaks(helpMap.get(lbl.getText().toLowerCase()),30);
                            lbl.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
                            }
                        }
                        
                        if(cmp instanceof JButton)
                        {
                            JButton btn = (JButton) cmp;
                            if(helpMap.containsKey(btn.getText().toLowerCase())) {
                            String tooltip = this.main.addLinebreaks(helpMap.get(btn.getText().toLowerCase()),30);
                            btn.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
                            }
                        }
                    }
                }
        }
    }
    
    void optPressureChanged() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    

 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        permgroup = new javax.swing.ButtonGroup();
        ensemblePanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        temperatureunitComboBox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        pressureTextField = new javax.swing.JTextField();
        pressureunitComboBox = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        densityTextField = new javax.swing.JTextField();
        densityunitComboBox = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        pistonmassTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        particlesTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        numberofcomponentsLabel = new javax.swing.JLabel();
        potmodeladdButton = new javax.swing.JButton();
        potmodelremoveButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        potmodelgeButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cutoffTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        epsilonTextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cutoffljTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cutoffddTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cutoffdqTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        cutoffqqTextField = new javax.swing.JTextField();
        potmodeltablelistScrollPane = new javax.swing.JScrollPane();
        potmodelTable = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        etaxiButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        calcMaxCutoff = new javax.swing.JButton();
        editPmFile = new javax.swing.JButton();
        vapdensityunitComboBox = new javax.swing.JComboBox();
        pistonmassunitComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ensemblesgeButton = new javax.swing.JButton();
        leftlastpanel = new javax.swing.JPanel();
        spanFunCFTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        viewFunCFTextField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        resFreqCFTextField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        corrLengthCFTextField = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        stepcorrfuntxt = new javax.swing.JTextField();
        transportComboBox = new javax.swing.JComboBox();
        jLabel46 = new javax.swing.JLabel();
        hamitoniantxt = new javax.swing.JTextField();
        hamiltonianlbl = new javax.swing.JLabel();
        enthalphytxt = new javax.swing.JTextField();
        enthalphylbl = new javax.swing.JLabel();
        vapDensityTextField = new javax.swing.JTextField();
        setHbondbtn = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        NumHbondcriteria = new javax.swing.JLabel();
        thermCondParabtn = new javax.swing.JButton();

        ensemblePanel.setPreferredSize(new java.awt.Dimension(603, 1030));

        jLabel22.setText("Temperature");

        temperatureTextField.setText("jTextField12");
        temperatureTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temperatureTextFieldFocusLost(evt);
            }
        });

        temperatureunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "K", "°C" }));

        jLabel23.setText("Pressure");
        jLabel23.setEnabled(false);

        pressureTextField.setText("jTextField13");
        pressureTextField.setEnabled(false);
        pressureTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pressureTextFieldFocusLost(evt);
            }
        });

        pressureunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MPa", "bar" }));
        pressureunitComboBox.setEnabled(false);

        jLabel25.setText("Density");

        densityTextField.setText("jTextField14");
        densityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                densityTextFieldFocusLost(evt);
            }
        });

        densityunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mol / l" }));

        jLabel27.setText("Piston mass");
        jLabel27.setEnabled(false);

        pistonmassTextField.setText("jTextField15");
        pistonmassTextField.setEnabled(false);
        pistonmassTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pistonmassTextFieldFocusLost(evt);
            }
        });

        jLabel28.setText("Number of particles");

        particlesTextField.setText("jTextField16");
        particlesTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                particlesTextFieldFocusLost(evt);
            }
        });

        jLabel30.setText("Number of components:");

        numberofcomponentsLabel.setText("n");

        potmodeladdButton.setText("Add component");
        potmodeladdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodeladdButtonActionPerformed(evt);
            }
        });

        potmodelremoveButton.setText("Remove component");
        potmodelremoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodelremoveButtonActionPerformed(evt);
            }
        });

        jLabel33.setText("Edit Component:");

        potmodelgeButton.setText("Grand Equilibrium Parameter");
        potmodelgeButton.setEnabled(false);
        potmodelgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodelgeButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("Cutoff");

        cutoffTextField.setText("jTextField22");
        cutoffTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffTextFieldFocusLost(evt);
            }
        });

        jLabel40.setText("electric constant ε");

        epsilonTextField.setText("1.0E10");
        epsilonTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                epsilonTextFieldFocusLost(evt);
            }
        });

        jLabel36.setText("LJ");
        jLabel36.setEnabled(false);
        jLabel36.setVerifyInputWhenFocusTarget(false);

        cutoffljTextField.setText("jTextField23");
        cutoffljTextField.setEnabled(false);
        cutoffljTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffljTextFieldFocusLost(evt);
            }
        });

        jLabel37.setText("D-D");
        jLabel37.setEnabled(false);

        cutoffddTextField.setText("jTextField24");
        cutoffddTextField.setEnabled(false);
        cutoffddTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffddTextFieldFocusLost(evt);
            }
        });

        jLabel38.setText("D-Q");
        jLabel38.setEnabled(false);

        cutoffdqTextField.setText("jTextField25");
        cutoffdqTextField.setEnabled(false);
        cutoffdqTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffdqTextFieldFocusLost(evt);
            }
        });

        jLabel39.setText("Q-Q");
        jLabel39.setEnabled(false);

        cutoffqqTextField.setText("jTextField26");
        cutoffqqTextField.setEnabled(false);
        cutoffqqTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffqqTextFieldFocusLost(evt);
            }
        });

        potmodeltablelistScrollPane.setPreferredSize(new java.awt.Dimension(453, 353));

        potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Potential Model", "Molar Fract.", "Permeability", "chemPotMethod"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        potmodelTable.setSurrendersFocusOnKeystroke(true);
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        potmodelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potmodelTableMouseClicked(evt);
            }
        });
        potmodeltablelistScrollPane.setViewportView(potmodelTable);

        jLabel26.setText("reduced");

        jLabel31.setText("reduced");

        jLabel32.setText("reduced");

        etaxiButton.setText("Eta & Xi");
        etaxiButton.setEnabled(false);
        etaxiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaxiButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Vapour Density");

        calcMaxCutoff.setText("Calculate max. Cutoff");
        calcMaxCutoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcMaxCutoffActionPerformed(evt);
            }
        });

        editPmFile.setText("Edit Model");
        editPmFile.setEnabled(false);
        editPmFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPmFileActionPerformed(evt);
            }
        });

        vapdensityunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mol / l" }));

        pistonmassunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "u / m^4" }));

        jLabel6.setText("reduced");

        jLabel7.setText("reduced");

        ensemblesgeButton.setText("Grand Equilibrium Parameter");
        ensemblesgeButton.setEnabled(false);
        ensemblesgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensemblesgeButtonActionPerformed(evt);
            }
        });

        spanFunCFTextField.setText("300");
        spanFunCFTextField.setEnabled(false);
        spanFunCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spanFunCFTextFieldfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spanFunCFTextFieldFocusLost(evt);
            }
        });

        jLabel41.setText("SpanCorrfun");
        jLabel41.setEnabled(false);

        viewFunCFTextField.setText("100");
        viewFunCFTextField.setEnabled(false);
        viewFunCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                viewFunCFTextFieldfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                viewFunCFTextFieldFocusLost(evt);
            }
        });

        jLabel42.setText("ViewCorrfun");
        jLabel42.setEnabled(false);

        resFreqCFTextField.setText("5");
        resFreqCFTextField.setEnabled(false);
        resFreqCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resFreqCFTextFieldfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resFreqCFTextFieldFocusLost(evt);
            }
        });

        jLabel43.setText("Correlation length");
        jLabel43.setEnabled(false);

        jLabel44.setText("CF result frequency");
        jLabel44.setEnabled(false);

        corrLengthCFTextField.setText("10000");
        corrLengthCFTextField.setEnabled(false);
        corrLengthCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                corrLengthCFTextFieldfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                corrLengthCFTextFieldFocusLost(evt);
            }
        });

        jLabel45.setText("Correlation function (CF) steps");
        jLabel45.setEnabled(false);

        stepcorrfuntxt.setText("5");
        stepcorrfuntxt.setEnabled(false);
        stepcorrfuntxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stepcorrfuntxtfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stepcorrfuntxtFocusLost(evt);
            }
        });

        transportComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Off", "On" }));
        transportComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportComboBoxActionPerformed(evt);
            }
        });

        jLabel46.setText("Transport Properties");

        org.jdesktop.layout.GroupLayout leftlastpanelLayout = new org.jdesktop.layout.GroupLayout(leftlastpanel);
        leftlastpanel.setLayout(leftlastpanelLayout);
        leftlastpanelLayout.setHorizontalGroup(
            leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftlastpanelLayout.createSequentialGroup()
                .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel45, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel44, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel46, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel43, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(resFreqCFTextField)
                    .add(corrLengthCFTextField)
                    .add(stepcorrfuntxt)
                    .add(transportComboBox, 0, 69, Short.MAX_VALUE))
                .add(33, 33, 33)
                .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(leftlastpanelLayout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jLabel42))
                    .add(jLabel41))
                .add(30, 30, 30)
                .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(spanFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(viewFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 52, Short.MAX_VALUE))
        );
        leftlastpanelLayout.setVerticalGroup(
            leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftlastpanelLayout.createSequentialGroup()
                .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(leftlastpanelLayout.createSequentialGroup()
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel41)
                            .add(spanFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel42)
                            .add(viewFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(leftlastpanelLayout.createSequentialGroup()
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel46)
                            .add(transportComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(8, 8, 8)
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel45)
                            .add(stepcorrfuntxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel43)
                            .add(corrLengthCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(leftlastpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel44)
                            .add(resFreqCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 0, Short.MAX_VALUE))
        );

        transportComboBox.getAccessibleContext().setAccessibleParent(ensemblePanel);

        hamitoniantxt.setText("jTextField12");
        hamitoniantxt.setEnabled(false);
        hamitoniantxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hamitoniantxtfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hamitoniantxtFocusLost(evt);
            }
        });

        hamiltonianlbl.setText("Hamiltonian");
        hamiltonianlbl.setEnabled(false);

        enthalphytxt.setText("jTextField12");
        enthalphytxt.setEnabled(false);
        enthalphytxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enthalphytxtfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enthalphytxtFocusLost(evt);
            }
        });

        enthalphylbl.setText("Enthalphy");
        enthalphylbl.setEnabled(false);

        vapDensityTextField.setText("jTextField14");
        vapDensityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vapDensityTextFieldfocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vapDensityTextFieldFocusLost(evt);
            }
        });

        setHbondbtn.setText("Set");
        setHbondbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setHbondbtnActionPerformed(evt);
            }
        });

        jLabel47.setText("Define H-Bond Criteria");

        jLabel48.setText("Number of Criteria");

        NumHbondcriteria.setText("0");

        thermCondParabtn.setText("Thermal Conductivity Parameters");
        thermCondParabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thermCondParabtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout ensemblePanelLayout = new org.jdesktop.layout.GroupLayout(ensemblePanel);
        ensemblePanel.setLayout(ensemblePanelLayout);
        ensemblePanelLayout.setHorizontalGroup(
            ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ensemblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(potmodeladdButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(potmodelremoveButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(calcMaxCutoff))
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel40, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(cutoffTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel36))
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(epsilonTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel37)))
                        .add(12, 12, 12)
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(cutoffljTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel38)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cutoffdqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(cutoffddTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel39)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cutoffqqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(leftlastpanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel28)
                                    .add(jLabel30)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, ensemblePanelLayout.createSequentialGroup()
                                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                    .add(jLabel1)
                                                    .add(jLabel27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(enthalphylbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(hamiltonianlbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(18, 18, 18))
                                            .add(ensemblePanelLayout.createSequentialGroup()
                                                .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(26, 26, 26)))
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(temperatureTextField)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, hamitoniantxt)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, enthalphytxt)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pressureTextField)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, densityTextField)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, vapDensityTextField)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pistonmassTextField))))
                                .add(19, 19, 19)
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(numberofcomponentsLabel)
                                    .add(particlesTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, pressureunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, densityunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, vapdensityunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, pistonmassunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(temperatureunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel26, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel32, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel31, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .add(potmodeltablelistScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 486, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(32, 32, 32)
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(potmodelgeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(editPmFile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(etaxiButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel33)
                            .add(ensemblesgeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(thermCondParabtn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel47)
                            .add(jLabel48))
                        .add(69, 69, 69)
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(NumHbondcriteria)
                            .add(setHbondbtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ensemblePanelLayout.setVerticalGroup(
            ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ensemblePanelLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ensemblesgeButton)
                    .add(jLabel22)
                    .add(temperatureTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(temperatureunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hamiltonianlbl)
                    .add(hamitoniantxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(enthalphylbl)
                    .add(enthalphytxt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pressureTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel23)
                    .add(pressureunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel31))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(densityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel25)
                    .add(densityunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel26))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(vapDensityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(vapdensityunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel32))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel27)
                    .add(pistonmassTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pistonmassunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(34, 34, 34)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28)
                    .add(particlesTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel30)
                    .add(numberofcomponentsLabel))
                .add(18, 18, 18)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(potmodeltablelistScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(jLabel33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(editPmFile)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(etaxiButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(potmodelgeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(thermCondParabtn)))
                .add(18, 18, 18)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(potmodeladdButton)
                    .add(potmodelremoveButton)
                    .add(calcMaxCutoff))
                .add(15, 15, 15)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(cutoffTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel36)
                    .add(cutoffljTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel38)
                    .add(cutoffdqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel24))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cutoffqqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel39)
                    .add(cutoffddTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(epsilonTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel37)
                    .add(jLabel40))
                .add(18, 18, 18)
                .add(leftlastpanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel47)
                    .add(setHbondbtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel48)
                    .add(NumHbondcriteria))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(ensemblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(ensemblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
   
    
    /**
     * Get specified Potential Model from the its table and pass it to editor.
     * 
     * @see PmEditor
     * 
     * @param evt 
     */
    private void editPmFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPmFileActionPerformed
        PotentialModel curPm = this.eData.potModelList.get(this.potmodelTable.getSelectedRow());
        new PmEditor(curPm).setVisible(true);
    }//GEN-LAST:event_editPmFileActionPerformed
    
    /**
     * @see EnsemblePanel#calcMaxCutoff()
     * 
     * @param evt 
     */
    private void calcMaxCutoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcMaxCutoffActionPerformed

        calcMaxCutoff();

    }//GEN-LAST:event_calcMaxCutoffActionPerformed
    
    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_focusGained
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void epsilonTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epsilonTextFieldFocusLost
        this.eData.setEps(this.main.validateInputDouble(this.epsilonTextField.getText()));
        this.epsilonTextField.setText(String.valueOf(this.eData.getEps()));
    }//GEN-LAST:event_epsilonTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void cutoffqqTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffqqTextFieldFocusLost
        this.eData.setCutOffQQ(this.main.validateInputDouble(this.cutoffqqTextField.getText()));
        this.cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
    }//GEN-LAST:event_cutoffqqTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void cutoffdqTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffdqTextFieldFocusLost
        this.eData.setCutOffDQ(this.main.validateInputDouble(this.cutoffdqTextField.getText()));
        this.cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
    }//GEN-LAST:event_cutoffdqTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void cutoffddTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffddTextFieldFocusLost
        this.eData.setCutOffDD(this.main.validateInputDouble(this.cutoffddTextField.getText()));
        this.cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
    }//GEN-LAST:event_cutoffddTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void cutoffljTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffljTextFieldFocusLost
        this.eData.setCutOffLJ(this.main.validateInputDouble(this.cutoffljTextField.getText()));
        this.cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
    }//GEN-LAST:event_cutoffljTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void cutoffTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffTextFieldFocusLost
        this.eData.setCutOff(this.main.validateInputDouble(this.cutoffTextField.getText()));
        this.cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
    }//GEN-LAST:event_cutoffTextFieldFocusLost
        
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void particlesTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_particlesTextFieldFocusLost
        this.eData.setNPart(this.main.validateInputInt(this.particlesTextField.getText()));
        this.particlesTextField.setText(String.valueOf(this.eData.getNPart()));
    }//GEN-LAST:event_particlesTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void pistonmassTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pistonmassTextFieldFocusLost
        this.eData.setPistonMass(this.main.validateInputDouble(this.pistonmassTextField.getText()));
        this.pistonmassTextField.setText(String.valueOf(this.eData.getPistonMass()));
    }//GEN-LAST:event_pistonmassTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void densityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_densityTextFieldFocusLost
        this.eData.setDensity(this.main.validateInputDouble(this.densityTextField.getText()));
        this.densityTextField.setText(String.valueOf(this.eData.getDensity()));
    }//GEN-LAST:event_densityTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void pressureTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pressureTextFieldFocusLost
        this.eData.setPressure(this.main.validateInputDouble(this.pressureTextField.getText()));
        this.pressureTextField.setText(String.valueOf(this.eData.getPressure()));
    }//GEN-LAST:event_pressureTextFieldFocusLost
    
    /**
     * Validates and save textfield data.
     * 
     * @param evt 
     */
    private void temperatureTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temperatureTextFieldFocusLost
        this.eData.setTemperature(this.main.validateInputDouble(this.temperatureTextField.getText()));
        this.temperatureTextField.setText(String.valueOf(this.eData.getTemperature()));
        this.main.saveFile = null;
    }//GEN-LAST:event_temperatureTextFieldFocusLost
    
    
    
    
/*
         Double newMolFrac = Double.valueOf(this.potmodelTable.getValueAt(0,this.potmodelTable.getSelectedRow()).toString()).doubleValue();
        this.eData.potModelList.get(this.potmodelTable.getSelectedRow()).setMolarFrac(newMolFrac);
 */
    /**
     * @see EnsemblePanel#updatePmButtons()
     * 
     * @param evt 
     */
    private void potmodelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potmodelTableMouseClicked
        
        updatePmButtons();
        
    }//GEN-LAST:event_potmodelTableMouseClicked
    
    /**
     * Show specified potential model into GePmJframe class.
     * 
     * @see GePmJFrame
     * 
     * @param evt 
     */
    private void potmodelgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodelgeButtonActionPerformed
        
        if (this.eData.potModelList.size() > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            if (row >= 0){
                
                PotentialModel curPm = this.eData.potModelList.get(row);
                
                //PotentialModel curPm = this.potmodelTable.getValueAt(0,row);
                
                new GePmJFrame(curPm).setVisible(true);
                
            }
        }
        
    }//GEN-LAST:event_potmodelgeButtonActionPerformed
    
    /**
     * Check and Remove specified potential model.
     * 
     * @param evt 
     */
    private void potmodelremoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodelremoveButtonActionPerformed
        
        if (this.eData.potModelList.size() > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            
            
            if (row >= 0){
                PotentialModel curPm = this.eData.potModelList.get(row);
                //PotentialModel curPm = this.potmodelTable.getValueAt(0,row);
                int ret;
                ret = JOptionPane.showConfirmDialog(new JFrame(), "Are you sure, you want to remove this Potential Model ?","Delete?", 0);
                if (ret==0){
                    //this.eData.potModelList.remove(row);
                    removeEtaXi(curPm);
                    this.eData.potModelList.remove(curPm);
                    
                    updatePmTable();
                } else {}
                
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "No Potential Model selected");
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "No Potential Model");
        }
        updatePmButtons();
        
    }//GEN-LAST:event_potmodelremoveButtonActionPerformed
    
    /**
     * Show
     * @see GeEnsembleFrame
     * @param evt 
     */
    private void ensemblesgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensemblesgeButtonActionPerformed
        JFrame GeEnsembleFrame = (new GeEnsembleJFrame(this.eData));
        GeEnsembleFrame.setVisible(true);
        
    }//GEN-LAST:event_ensemblesgeButtonActionPerformed
    
    /**
     * Set and show the etaxiPanel according to the size of the potential model table.
     * @see etaXiPanel
     * @param evt 
     */
    private void etaxiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaxiButtonActionPerformed

        int pmSize = this.eData.potModelList.size();
        if (pmSize > 1 ) {
            
            MatCompJPanel etaXiPanel = new MatCompJPanel();
            
            if (pmSize > 7) {
                etaXiPanel.setSize(1000,700);
            } else {
                etaXiPanel.setSize(pmSize*100+200,pmSize*75+100);
            }
            
            etaXiPanel.setVisible(true);
            
        }
  
    }//GEN-LAST:event_etaxiButtonActionPerformed
    
    /**
     * Set filters for potential model files
     * Populate potential model list by selected file and call potential model class.
     * 
     * @param evt 
     */
    private void potmodeladdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodeladdButtonActionPerformed
        int PmTabRows;
        
        String pmdirpathSelected;
        File pmfileSelected;
        File pmdirSelected;
        File pmdirDefault = null;
        
        class pmFilter extends FileFilter {
            public String getDescription() {
                return "Only Potential Model Files";
            }
            
            public boolean accept(File f) {
                if (f == null)
                    return false;
                if (f.isDirectory())
                    return true;
                return f.getName().toLowerCase().endsWith(".pm");
            }
        }
        
        JFileChooser pmfileChooser = new JFileChooser();
        pmfileChooser.addChoosableFileFilter(new pmFilter());
        pmfileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        pmfileChooser.setCurrentDirectory(pmdirDefault);
        int returnVal = pmfileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            pmdirSelected = pmfileChooser.getCurrentDirectory();
            pmfileSelected = pmfileChooser.getSelectedFile();
            pmdirpathSelected = pmdirSelected.getAbsolutePath();
            
            double molfrac=1.0;
            String perm = "No";
            if (this.eData.potModelList.size() > 0){
                
                Iterator pmIt = this.eData.potModelList.iterator();
                while (pmIt.hasNext()) {
                    PotentialModel pm = (PotentialModel)pmIt.next();
                    molfrac -= pm.getMolarFrac();
                    
                }
            }
            
            molfrac = Math.round(molfrac*10.)/10.;
            double input = -1.0;
            while (input < 0.0 || input > 1.0) {
                try {
                    input = this.main.validateInputDouble(JOptionPane.showInputDialog("Mole Fraction:",molfrac));
                } catch(Exception e) {
                    break;
                }
            }
            molfrac = input;
            
            if (input >= 0.0 && input <= 1.0) {
                PotentialModel pm = new PotentialModel(pmfileSelected, molfrac,"Yes");
                this.eData.potModelList.add(pm);
                
                if (this.eData.potModelList.size() > 1){
                    addEtaXi(pm);
                    
                }
            }
            
            updatePmTable();
            this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
            updatePmButtons();
            
        }
        
    }//GEN-LAST:event_potmodeladdButtonActionPerformed

    /**
     * 
     * @param evt 
     */
    private void spanFunCFTextFieldfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spanFunCFTextFieldfocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_spanFunCFTextFieldfocusGained

    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void spanFunCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spanFunCFTextFieldFocusLost
        this.eData.setspanFunCF(this.main.validateInputInt(this.spanFunCFTextField.getText()));
        this.spanFunCFTextField.setText(String.valueOf(this.eData.getspanFunCF()));
    }//GEN-LAST:event_spanFunCFTextFieldFocusLost

    private void viewFunCFTextFieldfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewFunCFTextFieldfocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_viewFunCFTextFieldfocusGained
    
    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void viewFunCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewFunCFTextFieldFocusLost
        this.eData.setviewFunCF(this.main.validateInputInt(this.viewFunCFTextField.getText()));
        this.viewFunCFTextField.setText(String.valueOf(this.eData.getviewFunCF()));
    }//GEN-LAST:event_viewFunCFTextFieldFocusLost

    private void resFreqCFTextFieldfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resFreqCFTextFieldfocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_resFreqCFTextFieldfocusGained
    
    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void resFreqCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resFreqCFTextFieldFocusLost
        this.eData.setresFreqCF(this.main.validateInputInt(this.resFreqCFTextField.getText()));
        this.resFreqCFTextField.setText(String.valueOf(this.eData.getresFreqCF()));
    }//GEN-LAST:event_resFreqCFTextFieldFocusLost

    private void corrLengthCFTextFieldfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_corrLengthCFTextFieldfocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_corrLengthCFTextFieldfocusGained
    
    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void corrLengthCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_corrLengthCFTextFieldFocusLost
        this.eData.setcorrLengthCF(this.main.validateInputInt(this.corrLengthCFTextField.getText()));
        this.corrLengthCFTextField.setText(String.valueOf(this.eData.getcorrLengthCF()));
    }//GEN-LAST:event_corrLengthCFTextFieldFocusLost

    private void stepcorrfuntxtfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stepcorrfuntxtfocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_stepcorrfuntxtfocusGained

    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void stepcorrfuntxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stepcorrfuntxtFocusLost
        this.eData.setstepFunCF(this.main.validateInputInt(this.stepcorrfuntxt.getText()));
        this.stepcorrfuntxt.setText(String.valueOf(this.eData.getstepFunCF()));
    }//GEN-LAST:event_stepcorrfuntxtFocusLost
    
    /**
     * On transport value change
     * 
     * @see FileGenGUI#transportChanged(ms_newpars.EnsemblePanel)
     * 
     * @param evt 
     */
    private void transportComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportComboBoxActionPerformed
        this.main.transportChanged(this);
    }//GEN-LAST:event_transportComboBoxActionPerformed

    private void hamitoniantxtfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hamitoniantxtfocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hamitoniantxtfocusGained

    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void hamitoniantxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hamitoniantxtFocusLost
        this.eData.setHamiltonian(this.main.validateInputDouble(this.hamitoniantxt.getText()));
        this.hamitoniantxt.setText(String.valueOf(this.eData.getHamiltonian()));
    }//GEN-LAST:event_hamitoniantxtFocusLost

    private void enthalphytxtfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enthalphytxtfocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_enthalphytxtfocusGained
    
    /**
     * validate and save input value.
     * 
     * @param evt 
     */
    private void enthalphytxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enthalphytxtFocusLost
        this.eData.setEnthalphy(this.main.validateInputDouble(this.enthalphytxt.getText()));
        this.enthalphytxt.setText(String.valueOf(this.eData.getEnthalphy()));
    }//GEN-LAST:event_enthalphytxtFocusLost

    private void vapDensityTextFieldfocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vapDensityTextFieldfocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_vapDensityTextFieldfocusGained

    /**
     * Validate and save input value.
     * 
     * @param evt 
     */
    private void vapDensityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vapDensityTextFieldFocusLost
        if (this.vapDensityTextField.getText().length() > 0){
            this.eData.setVapDensity(this.main.validateInputDouble(this.vapDensityTextField.getText()));
            this.vapDensityTextField.setText(String.valueOf(this.eData.getVapDensity()));
        } else {
            //this.eData.setVapDensity(null);
        }
    }//GEN-LAST:event_vapDensityTextFieldFocusLost
    
    /**
     * On set Hbond Criteria
     * 
     * @see HbondCriteria
     * 
     * @param evt 
     */
    private void setHbondbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setHbondbtnActionPerformed
        HbondCriteria cr = new HbondCriteria(this,this.eData.hbondcriteria);
        cr.setVisible(true);
    }//GEN-LAST:event_setHbondbtnActionPerformed
    
    /**
     * @see TherCondparam
     * @param evt 
     */
    private void thermCondParabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thermCondParabtnActionPerformed
        PotentialModel curPm = this.eData.potModelList.get(this.potmodelTable.getSelectedRow());
        new TherCondparam(curPm);
    }//GEN-LAST:event_thermCondParabtnActionPerformed

    /**
     * Prepare and save comments for the Potential Model.
     */
    public void getEtaxiComments()
    {
        //JOptionPane.showMessageDialog(null, potmodelTable.getRowCount());
        
        if(this.potmodelTable.getRowCount() > 0)
        {
        
        int count = 0;
        for(int i=0;i<this.potmodelTable.getRowCount()-1;i++)
        {
                      for(int j=i+1;j<this.potmodelTable.getRowCount();j++)
                      {
                          this.eData.Commentsdata.add(count,this.potmodelTable.getValueAt(i, 0) + " and "+this.potmodelTable.getValueAt(j, 0));
                          //JOptionPane.showMessageDialog(null, this.eData.Commentsdata.get(count));
                          count++;
                      }
        }
        }
        
    }

    /**
     * Add eta and xi values to a specified Potential Model.
     * 
     * @param pm Potential Model
     */
    public void addEtaXi(PotentialModel pm) {
        LinkedList pmList = this.eData.potModelList;
        
        /* Insert first EtaXi for 2nd Model */
        if (this.eData.getEtaxi() == null){
            this.eData.setEtaxi(new EtaXi((PotentialModel) pmList.get(0),pm));
            this.eData.setLast(this.eData.getEtaxi());
        } else {
            EtaXi cur = this.eData.getEtaxi();
            int i = 0;
            while (cur != this.eData.getLast()){
                /* Insert EtaXi at row end */
                if (cur.getRowEnd()){
                    EtaXi newEtaXi = new EtaXi((PotentialModel) pmList.get(i),pm);
                    newEtaXi.setNext(cur.getNext());
                    cur.setNext(newEtaXi);
                    cur.setRowEnd(false);
                    cur = cur.getNext();
                    i++;
                }
                
                cur = cur.getNext();
            }
            cur.setRowEnd(false);
            /* Add EtaXi after last Element*/
            cur.setNext(new EtaXi((PotentialModel) pmList.get(i),pm));
            this.eData.setLast(this.eData.getLast().getNext());
            i++;
            /* Add last EtaXi */
            this.eData.getLast().setNext(new EtaXi((PotentialModel) pmList.get(i),pm));
            this.eData.setLast(this.eData.getLast().getNext());
            
        }
    }
    
    /**
     * Remove eta and xi values from specific potential model.
     * 
     * @param pm 
     */
    private void removeEtaXi(PotentialModel pm){
        
        EtaXi cur = this.eData.getEtaxi();
        EtaXi prev = null;
        while(cur !=null){
            if (cur.getPm1()==pm || cur.getPm2()==pm){
                if (cur == this.eData.getEtaxi()){
                    this.eData.setEtaxi(cur.getNext());
                } else if (cur==this.eData.getLast()){
                    this.eData.setLast(prev);
                    prev.setNext(null);
                } else{
                    prev.setNext(cur.getNext());
                }
            }
            prev = cur;
            cur = cur.getNext();
        }
        
    }
    
    /**
     * Creates new Ensemble panel.
     */
    public void initPanel() {
        
        this.eData = new Ensemble();
        this.eData.potModelList = new LinkedList<PotentialModel>();
        
        updateEnsemblePanel();
        
    }
    
    /**
     * Set and assign saved values to UI controls in Ensemble panel.
     */
    public void updateEnsemblePanel() {
        
        temperatureTextField.setText(String.valueOf(this.eData.getTemperature()));
        hamitoniantxt.setText(String.valueOf(this.eData.getHamiltonian()));
        enthalphytxt.setText(String.valueOf(this.eData.getEnthalphy()));
        pressureTextField.setText(String.valueOf(this.eData.getPressure()));
        densityTextField.setText(String.valueOf(this.eData.getDensity()));
        vapDensityTextField.setText(String.valueOf(this.eData.getVapDensity()));
        pistonmassTextField.setText(String.valueOf(this.eData.getPistonMass()));
        jLabel27.setEnabled(false);
        pistonmassTextField.setEnabled(false);
        pistonmassunitComboBox.setEnabled(false);
        particlesTextField.setText(String.valueOf(this.eData.getNPart()));
        
        NumHbondcriteria.setText(String.valueOf(this.eData.numofcriteria));
        
        cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
        cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
        cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
        cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
        cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
        epsilonTextField.setText(String.valueOf(this.eData.getEps()));
        
        //jLabel40.setEnabled(true);
       // if(this.main.iscorrfunup)
        transportComboBox.setSelectedItem(this.main.eData.getTransport());
       // else
           // transportComboBox.setSelectedItem(this.eData.getTransport());
//       transportComboBox.setSelectedItem(this.main.eData.getTransport());
       //JOptionPane.showMessageDialog(null, "in ensemble update : "+transportComboBox.getSelectedItem().toString());
        stepcorrfuntxt.setText(String.valueOf(this.eData.getstepFunCF()));
        resFreqCFTextField.setText(String.valueOf(this.eData.getresFreqCF()));
        corrLengthCFTextField.setText(String.valueOf(this.eData.getcorrLengthCF()));
        spanFunCFTextField.setText(String.valueOf(this.eData.getspanFunCF()));
        viewFunCFTextField.setText(String.valueOf(this.eData.getviewFunCF()));

        if (this.main.systemofunitsComboBox.getSelectedItem().toString().equals("SI")){
            
            jLabel26.setVisible(false);
            jLabel31.setVisible(false);
            jLabel32.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            
        } else {
            this.temperatureunitComboBox.setVisible(false);
            this.pressureunitComboBox.setVisible(false);
            this.densityunitComboBox.setVisible(false);
             
        }
        if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("GE")){
            this.ensemblesgeButton.setEnabled(true);
            
        }
        if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NPT")){
            this.pressureTextField.setEnabled(true);
            this.pressureunitComboBox.setEnabled(true);
            if (this.main.typeofsimulationComboBox.getSelectedItem().toString().equals("MD")){
                this.pistonmassTextField.setEnabled(true);
            }
            
        }
       
        
        updatePmTable();
        updatePmButtons();
    }
   
    /**
     * create potential model table.
     */
   private void initPmTable() {
        
        potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String [] {"Pot. Model", "Mole Fract.", "Permeability", "ChemPotMethod"}
        )
        );
        
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        
        this.potmodelTable.getColumnModel().getColumn(0).setCellRenderer( this.potmodelTable.getTableHeader().getDefaultRenderer() );
        this.potmodelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    /**
     * Enable or disable potential model button according to the specified ensemble selected.
     */
    public void updatePmButtons(){
        int pmNum = this.eData.potModelList.size();
        if (pmNum > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            if (row >= 0){
                this.editPmFile.setEnabled(true);
                if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("GE")){
                    this.potmodelgeButton.setEnabled(true);
                    //this.potmodelgeButton.setVisible(true);
//                    this.chemPotMethodjButton.setEnabled(false); in the potmod table
                    this.thermCondParabtn.setEnabled(false);
                    //this.chemPotMethodjButton.setVisible(false);
                } else{
                    this.potmodelgeButton.setEnabled(false);
                    //this.potmodelgeButton.setVisible(false);
//                    this.chemPotMethodjButton.setEnabled(true); in the potmod table...
                    this.thermCondParabtn.setEnabled(true);
                    //this.chemPotMethodjButton.setVisible(true);
                }
            } else {
                this.editPmFile.setEnabled(false);
                this.potmodelgeButton.setEnabled(false);
//                this.chemPotMethodjButton.setEnabled(false); in the potmod table
                this.thermCondParabtn.setEnabled(false);
            }
            if (this.eData.potModelList.size() > 1 ) {
                this.etaxiButton.setEnabled(true);
            } else{
                this.etaxiButton.setEnabled(false);
            }
        } else {
            this.etaxiButton.setEnabled(false);
            this.potmodelgeButton.setEnabled(false);
//            this.chemPotMethodjButton.setEnabled(false); in the potmod table
            this.thermCondParabtn.setEnabled(false);
            this.editPmFile.setEnabled(false);
        }
        
    }
    
    /**
     * Update potential model table.
     */
    public void updatePmTable() {
        if (this.eData.potModelList.size() > 0){
            
            Object[][] pmObjArray = new Object [this.eData.potModelList.size()][3];
            
            for (int i=0; i < pmObjArray.length; i++) {
                
                PotentialModel curPm = this.eData.potModelList.get(i);
                
                pmObjArray[i][0] = curPm.getName();
                pmObjArray[i][1] = curPm.getMolarFrac();
                pmObjArray[i][2] = curPm.getpermeablity();
            }
            potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
                    (Object[][]) pmObjArray ,
                    new String [] {"Pot. Model", "Mole Fract.", "Permeability", "ChemPotMethod"}
            )
            );
            getEtaxiComments();
        } else {
            initPmTable();
        }
        
        this.potmodelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.potmodelTable.getColumnModel().getColumn(0).setCellEditor(new NoTableCellEditor());
        this.potmodelTable.getColumnModel().getColumn(1).setCellEditor(new pmTableCellEditor());
        this.potmodelTable.getColumnModel().getColumn(2).setCellEditor(rowEditor);
        this.potmodelTable.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());
        this.potmodelTable.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JCheckBox()));
        this.potmodelTable.getColumnModel().getColumn(0).setCellRenderer( this.potmodelTable.getTableHeader().getDefaultRenderer() );
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        
        if(this.eData.potModelList.size() > 0)
        {
                            addtablelistnerforJcombobox();
                            addcomboToPotModelTable();
        }
        
    }
    
    /**
     * Overide cell editor of potential model table to make cell non-editable.
     */
    public class NoTableCellEditor extends AbstractCellEditor implements TableCellEditor {
        
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int rowIndex, int vColIndex) {
            return null;
        }
        
        public Object getCellEditorValue() {
            return null;
        }
    }
    
    /**
     * override cell editor of potential model table.
     */
    public class pmTableCellEditor extends AbstractCellEditor implements TableCellEditor {
        
        JComponent component = new JTextField();
        
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int col) {
            
            ((JTextField)component).setText(String.valueOf(value));
            
            return component;
        }
        
        public Object getCellEditorValue() {
            EnsemblePanel curE = (EnsemblePanel) main.ensemblesTabbedPane.getSelectedComponent();
            PotentialModel pm = curE.eData.potModelList.get(curE.potmodelTable.getSelectedRow());
            double molfrac = Double.valueOf(((JTextField)component).getText());
            pm.setMolarFrac(molfrac);
            return ((JTextField)component).getText();
        }
        
    }
    
    /**
     * add button in the cell of potential model table.
     */
    class ButtonRenderer extends JButton implements TableCellRenderer {
        
        public ButtonRenderer() {
          setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
          if (isSelected) {
            setForeground(table.getSelectionForeground());
            setBackground(table.getSelectionBackground());
          } else {
            setForeground(table.getForeground());
            setBackground(UIManager.getColor("Button.background"));
          }
          setText((value == null) ? "View" : value.toString());
          return this;
        }
    }
    class ButtonEditor extends DefaultCellEditor {
        protected JButton button;

        private String label;

        public ButtonEditor(JCheckBox checkBox) {
          super(checkBox);
          button = new JButton();
          button.setOpaque(true);
          button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                PotentialModel curPm = eData.potModelList.get(potmodelTable.getSelectedRow());
                new ChemPotMethodJFrame(curPm).setVisible(true);
              fireEditingStopped();
            }
          });
        }

        public Component getTableCellEditorComponent(JTable table, Object value,
            boolean isSelected, int row, int column) {
          if (isSelected) {
            button.setForeground(table.getSelectionForeground());
            button.setBackground(table.getSelectionBackground());
          } else {
            button.setForeground(table.getForeground());
            button.setBackground(table.getBackground());
          }
          label = (value == null) ? "View" : value.toString();
          button.setText(label);
          return button;
        }
        
        public Object getCellEditorValue() {
          return new String(label);
        }

        public boolean stopCellEditing() {
          return super.stopCellEditing();
        }

        protected void fireEditingStopped() {
          super.fireEditingStopped();
        }
}
    //end table cell button
    
    /**
     * To get the value of dropdown from the potmodeltable and
     * set its value in pm model when ever user changes the value in order to
     * use it later.
     */
    private void addtablelistnerforJcombobox(){
        this.potmodelTable.getModel().addTableModelListener(new TableModelListener(){

            @Override
            public void tableChanged(TableModelEvent e) {
                int index = e.getColumn();
                     System.out.println(index);
                    if(e.getType() == TableModelEvent.UPDATE)
                    {
                        if(potmodelTable.getSelectedRow() > -1)
                        {
                          if(index == 2)
                            {
                                EnsemblePanel curE = (EnsemblePanel) main.ensemblesTabbedPane.getSelectedComponent();
                                PotentialModel pm = curE.eData.potModelList.get(curE.potmodelTable.getSelectedRow());
                                pm.setpermeability(String.valueOf(potmodelTable.getValueAt(potmodelTable.getSelectedRow(), index)));
                                System.out.println(String.valueOf(potmodelTable.getValueAt(potmodelTable.getSelectedRow(), index)));
                                System.out.println(pm.getpermeablity());
                            }
                        }
                        
                    }
                  }
            
            
        });
    }
    
    /**
     * Calculating the value of maximum cutOff depending on the system of units and
     * the value of the density.
     */
    private void calcMaxCutoff(){
        
        if (this.main.gData.getLengthUnit()==0.0)
            JOptionPane.showMessageDialog(new JFrame()," LenghtUnit = 0.0 ");
        else if (this.eData.getNPart()==0)
            JOptionPane.showMessageDialog(new JFrame()," NParticles = 0 ");
        else if (this.eData.getDensity()==0.0)
            JOptionPane.showMessageDialog(new JFrame()," Density = 0.0 ");
        else {
                
            double maxCutoff;
            double density = this.eData.getDensity();
            if ((this.main.systemofunitsComboBox.getSelectedItem().toString().equals("SI"))){
                density = (density*1E-27)*(6.022E23)*(Math.pow(this.main.gData.getLengthUnit(),3.));
      
            }
            maxCutoff = (this.eData.getNPart())/density;

            maxCutoff = 0.5 * Math.pow(maxCutoff, 1./3.) ;
            maxCutoff = Math.round(maxCutoff*100.)/100.;
 
                    
            if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NVE") ||this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NVT")){
                    this.eData.setCutOff(maxCutoff);
                    
                    this.eData.setCutOffLJ(maxCutoff);
                    this.eData.setCutOffDD(maxCutoff);
                    this.eData.setCutOffDQ(maxCutoff);
                    this.eData.setCutOffQQ(maxCutoff);
                    if (this.main.cutofftypeComboBox.getSelectedItem().toString().equals("COM")){
                        
                        this.cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
                    }                     
                    else{
                        
                        this.cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
                        this.cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
                        this.cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
                        this.cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
                    }                      
            }
            else{
                FileGenGUI parent2 = this.main;
                Ensemble parent1 = this.eData;          
                this.eData.setCutOff(maxCutoff);
               
                this.cutoffTextField.setEnabled(false);
                this.jLabel24.setEnabled(false);
                new changeMaxCutoffJFrame(parent1,this,parent2).setVisible(true);
           }
 
        }
        
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel NumHbondcriteria;
    public javax.swing.JButton calcMaxCutoff;
    public javax.swing.JTextField corrLengthCFTextField;
    public javax.swing.JTextField cutoffTextField;
    public javax.swing.JTextField cutoffddTextField;
    public javax.swing.JTextField cutoffdqTextField;
    public javax.swing.JTextField cutoffljTextField;
    public javax.swing.JTextField cutoffqqTextField;
    public javax.swing.JTextField densityTextField;
    public javax.swing.JComboBox densityunitComboBox;
    private javax.swing.JButton editPmFile;
    public javax.swing.JPanel ensemblePanel;
    public javax.swing.JButton ensemblesgeButton;
    public javax.swing.JLabel enthalphylbl;
    public javax.swing.JTextField enthalphytxt;
    public javax.swing.JTextField epsilonTextField;
    private javax.swing.JButton etaxiButton;
    public javax.swing.JLabel hamiltonianlbl;
    public javax.swing.JTextField hamitoniantxt;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel41;
    public javax.swing.JLabel jLabel42;
    public javax.swing.JLabel jLabel43;
    public javax.swing.JLabel jLabel44;
    public javax.swing.JLabel jLabel45;
    public javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel leftlastpanel;
    public javax.swing.JLabel numberofcomponentsLabel;
    public javax.swing.JTextField particlesTextField;
    private javax.swing.ButtonGroup permgroup;
    public javax.swing.JTextField pistonmassTextField;
    public javax.swing.JComboBox pistonmassunitComboBox;
    public javax.swing.JTable potmodelTable;
    public javax.swing.JButton potmodeladdButton;
    public javax.swing.JButton potmodelgeButton;
    private javax.swing.JButton potmodelremoveButton;
    private javax.swing.JScrollPane potmodeltablelistScrollPane;
    public javax.swing.JTextField pressureTextField;
    public javax.swing.JComboBox pressureunitComboBox;
    public javax.swing.JTextField resFreqCFTextField;
    private javax.swing.JButton setHbondbtn;
    public javax.swing.JTextField spanFunCFTextField;
    public javax.swing.JTextField stepcorrfuntxt;
    public javax.swing.JTextField temperatureTextField;
    public javax.swing.JComboBox temperatureunitComboBox;
    public javax.swing.JButton thermCondParabtn;
    public javax.swing.JComboBox transportComboBox;
    public javax.swing.JTextField vapDensityTextField;
    public javax.swing.JComboBox vapdensityunitComboBox;
    public javax.swing.JTextField viewFunCFTextField;
    // End of variables declaration//GEN-END:variables
    
    /**
     *
     */
    public Ensemble eData;
    // public EnsemblePanel fData;
    private FileGenGUI main;
    private HashMap<String,String> helpMap;
}
