/*
 * GeEnsembleJPanel.java
 *
 * Created on 10. November 2006, 11:17
 */

package ms_newpars;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  berreth
 */
public class GeEnsembleJFrame extends javax.swing.JFrame {
    
    /** Creates new form GeEnsembleJPanel
     * @param ensembleData */
    public GeEnsembleJFrame(Ensemble ensembleData) {
        initComponents();
        this.edata = ensembleData;
        updateEnsembleGePanel();
        //initTooltips();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        pressure0 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        liqdensity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vardensity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        liqenthalpie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        varenthalpie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        liqbetat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        varbetat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        liqdhdp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        vardhdp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GE-Parameters");
        jLabel1.setText("Pressure0");
        jLabel1.setToolTipText("Test Tooltip Pressure0");

        pressure0.setText("0.0");
        pressure0.setToolTipText("Tooltip Pressure0 Textfield");

        jLabel2.setText("Density");

        liqdensity.setText("0.0");

        jLabel3.setText("Density");

        vardensity.setText("0.0");

        jLabel4.setText("Enthalpie");

        liqenthalpie.setText("0.0");

        jLabel5.setText("Enthalpie");

        varenthalpie.setText("0.0");

        jLabel6.setText("BetaT");

        liqbetat.setText("0.0");

        jLabel7.setText("BetaT");

        varbetat.setText("0.0");

        jLabel8.setText("dHdp");

        liqdhdp.setText("0.0");

        jLabel9.setText("dHdp");

        vardhdp.setText("0.0");

        jLabel10.setText("Results from liquid run for phase equilibrium");

        jLabel11.setText("Liquid");

        jLabel12.setText("Var");

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(23, 23, 23)
                        .add(pressure0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(layout.createSequentialGroup()
                                            .add(jLabel2)
                                            .add(20, 20, 20)
                                            .add(liqdensity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(layout.createSequentialGroup()
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                    .add(jLabel4)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                                .add(layout.createSequentialGroup()
                                                    .add(jLabel6)
                                                    .add(35, 35, 35)))
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(liqbetat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(liqenthalpie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(liqdhdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(1, 1, 1)))))
                            .add(jLabel11))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel5)
                                    .add(jLabel3)
                                    .add(jLabel7)
                                    .add(jLabel9))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(vardhdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(vardensity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(varenthalpie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(varbetat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel12)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel10)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(pressure0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(liqdensity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(vardensity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(liqenthalpie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(varenthalpie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(liqbetat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(varbetat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(liqdhdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(vardhdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GePanelToEnsembleData();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     *
     * @param str
     * 
     * This function validates double value.
     * 
     * @return
     */
    public double validateInputDouble(String str){
        double ret = 0.0;
        if (str.length() > 0) {
            try {
                ret = Double.valueOf(str).doubleValue();
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid decimal number.");
            }
        }
        return ret;
    }
    
    /**
     *
     * @param str
     * this function validates Integer value.
     * @return
     */
    public int validateInputInt(String str){
        int ret = 0;
        if (str.length() > 0) {
            try {
                ret = Integer.parseInt(str);
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid number.");
            }
        }
        
        return ret;
    }
    
   
    /**
     * This function updates the values in the ensemble panel
     */
    private void updateEnsembleGePanel(){
        pressure0.setText(String.valueOf(this.edata.getGePressure0()));
        liqdensity.setText(String.valueOf(this.edata.getGeLiqDensity()));
        vardensity.setText(String.valueOf(this.edata.getGeVarDensity()));
        liqenthalpie.setText(String.valueOf(this.edata.getGeLiqEnthalp()));
        varenthalpie.setText(String.valueOf(this.edata.getGeVarEnthalp()));
        liqbetat.setText(String.valueOf(this.edata.getGeLiqBetaT()));
        varbetat.setText(String.valueOf(this.edata.getGeVarBetaT()));
        liqdhdp.setText(String.valueOf(this.edata.getGeLiqdHdP()));
        vardhdp.setText(String.valueOf(this.edata.getGeVardHdP()));
    }
    
    private void GePanelToEnsembleData(){
        
        this.edata.setGePressure0(this.validateInputDouble(this.pressure0.getText()));
        this.edata.setGeLiqDensity(this.validateInputDouble(this.liqdensity.getText()));
        this.edata.setGeLiqEnthalp(this.validateInputDouble(this.liqenthalpie.getText()));
        this.edata.setGeLiqBetaT(this.validateInputDouble(this.liqbetat.getText()));
        this.edata.setGeLiqdHdP(this.validateInputDouble(this.liqdhdp.getText()));
        this.edata.setGeVarDensity(this.validateInputDouble(this.vardensity.getText()));
        this.edata.setGeVarEnthalp(this.validateInputDouble(this.varenthalpie.getText()));
        this.edata.setGeVarBetaT(this.validateInputDouble(this.varbetat.getText()));
        this.edata.setGeVardHdP(this.validateInputDouble(this.vardhdp.getText()));
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField liqbetat;
    public javax.swing.JTextField liqdensity;
    public javax.swing.JTextField liqdhdp;
    public javax.swing.JTextField liqenthalpie;
    public javax.swing.JTextField pressure0;
    public javax.swing.JTextField varbetat;
    public javax.swing.JTextField vardensity;
    public javax.swing.JTextField vardhdp;
    public javax.swing.JTextField varenthalpie;
    // End of variables declaration//GEN-END:variables
    private Ensemble edata;
}
