/*
 * GePmJFrame.java
 *
 * Created on 10. November 2006, 11:35
 */

package ms_newpars;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  berreth
 */
public class GePmJFrame extends javax.swing.JFrame {
    
    /** Creates new form GePmJFrame
     * @param potModel */
    public GePmJFrame(PotentialModel potModel) {
        initComponents();
        
        pm = potModel;
        
        this.jLabel8.setText(this.pm.getName());
        updatePmGePanel();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        liqmolfract = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chempot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        varchempot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        partmolvol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        varpartmolvol = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GE-Parameters for each Potential Model");

        jLabel1.setText("Mole Fraction");

        liqmolfract.setText("0.0");

        jLabel2.setText("Chem Pot");

        chempot.setText("0.0");

        jLabel3.setText("Chem Pot");

        varchempot.setText("0.0");

        jLabel4.setText("Part Mol Vol");

        partmolvol.setText("0.0");

        jLabel5.setText("Part mol Vol");

        varpartmolvol.setText("0.0.");

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Results from liquid run for phase equilibrium");

        jLabel7.setText("for component");

        jLabel8.setText("PM_1");

        jLabel9.setText("Liquid");

        jLabel10.setText("Var");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel8))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(liqmolfract, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(chempot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(partmolvol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel5)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(varpartmolvol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(jLabel3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(varchempot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                    .add(jLabel9))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(liqmolfract, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(varchempot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(chempot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(varpartmolvol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(partmolvol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PmGePanelToEnsembleData();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *
     * @param str
     * @return
     */
    public double validateInputDouble(String str){
        double ret = 0.0;
        if (str.length() > 0) {
            try {
                ret = Double.valueOf(str).doubleValue();
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid decimal number.");
            }
        }
        return ret;
    }
    
    /**
     *
     * @param str
     * @return
     */
    public int validateInputInt(String str){
        int ret = 0;
        if (str.length() > 0) {
            try {
                ret = Integer.parseInt(str);
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid number.");
            }
        }
        
        return ret;
    }
    
    private void updatePmGePanel(){
        this.liqmolfract.setText(String.valueOf(this.pm.getGeMolarFrac()));
        this.chempot.setText(String.valueOf(this.pm.getGeLiqChemPot()));
        this.partmolvol.setText(String.valueOf(this.pm.getGeLiqPartMolVol()));
        this.varchempot.setText(String.valueOf(this.pm.getGeVarChemPot()));
        this.varpartmolvol.setText(String.valueOf(this.pm.getGeVarPartMolVol()));

    }
    
    private void PmGePanelToEnsembleData(){
        this.pm.setGeMolarFrac(this.validateInputDouble(this.liqmolfract.getText()));
        this.pm.setGeLiqChemPot(this.validateInputDouble(this.chempot.getText()));
        this.pm.setGeLiqPartMolVol(this.validateInputDouble(this.partmolvol.getText()));
        this.pm.setGeVarChemPot(this.validateInputDouble(this.varchempot.getText()));
        this.pm.setGeVarPartMolVol(this.validateInputDouble(this.varpartmolvol.getText()));
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField chempot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField liqmolfract;
    public javax.swing.JTextField partmolvol;
    public javax.swing.JTextField varchempot;
    public javax.swing.JTextField varpartmolvol;
    // End of variables declaration//GEN-END:variables
    private PotentialModel pm;
}
