/*
    this is the project for university of kaiserslautern..... thermodynamics lab...

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ms_newpars;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Syed Ahsan Ali
 */
public class HbondCriteria extends javax.swing.JFrame {

    /**
     * Creates new form HbondCriteria
     */
    ArrayList<ArrayList<Object>> criteria = new ArrayList<ArrayList<Object>>();
    EnsemblePanel main;
    int numofcriteria = 0;
    String[] dval = {"1","1","1","1","1","1","1.0","1.0","1.0"};

    /**
     *
     * @param parent
     * @param hbondcriteria
     */
    public HbondCriteria(EnsemblePanel parent, ArrayList<ArrayList<Object>> hbondcriteria) {
        initComponents();
        this.main = parent;
        ((DefaultEditor) criteriaspinner.getEditor()).getTextField().setEditable(false);
        if(hbondcriteria != null)
        {
            criteria = hbondcriteria;
            setcriteriaspinner();
        }
        
        this.delCriteriabtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hbondcriteriapanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Hbondsavebtn = new javax.swing.JButton();
        statuslbl = new javax.swing.JLabel();
        delCriteriabtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        criteriaspinnerlbl = new javax.swing.JLabel();
        criteriaspinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel10.setText("AngleCrit [φ AAD]");

        jTextField9.setText("1");
        jTextField9.setName(""); // NOI18N

        jTextField8.setText("1.0");
        jTextField8.setName("Double"); // NOI18N
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValidationOnFocusLost(evt);
            }
        });

        jLabel9.setText("DistCrit2[ℓ AD]");

        jLabel8.setText("DistCrit1[ℓ AA]");

        jTextField7.setText("1");
        jTextField7.setName(""); // NOI18N
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IntegerValidationOnFocusLost(evt);
            }
        });

        jTextField6.setText("1");
        jTextField6.setName(""); // NOI18N

        jLabel7.setText("DonDonSite:");

        jTextField1.setText("1");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IntegerValidationOnFocusLost(evt);
            }
        });

        jLabel2.setText("AccComp:");

        jLabel3.setText("AccAccSite:");

        jTextField2.setText("1");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IntegerValidationOnFocusLost(evt);
            }
        });

        jLabel4.setText("AccDonSite:");

        jTextField3.setText("1.0");
        jTextField3.setName("Double"); // NOI18N
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValidationOnFocusLost(evt);
            }
        });

        jLabel5.setText("DonComp:");

        jTextField4.setText("1.0");
        jTextField4.setName("Double"); // NOI18N
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValidationOnFocusLost(evt);
            }
        });

        jLabel6.setText("DonAccSite:");

        jTextField5.setText("1");
        jTextField5.setName(""); // NOI18N

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Hbondsavebtn.setText("Save");
        Hbondsavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbondsavebtnActionPerformed(evt);
            }
        });

        statuslbl.setText("...");

        delCriteriabtn.setText("delete");
        delCriteriabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCriteriabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hbondcriteriapanelLayout = new javax.swing.GroupLayout(hbondcriteriapanel);
        hbondcriteriapanel.setLayout(hbondcriteriapanelLayout);
        hbondcriteriapanelLayout.setHorizontalGroup(
            hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hbondcriteriapanelLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(statuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(delCriteriabtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hbondsavebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addGap(18, 18, 18)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        hbondcriteriapanelLayout.setVerticalGroup(
            hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hbondcriteriapanelLayout.createSequentialGroup()
                                .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hbondcriteriapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hbondsavebtn)
                            .addComponent(statuslbl)
                            .addComponent(delCriteriabtn)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        criteriaspinnerlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        criteriaspinnerlbl.setText("Add Criteria:");

        criteriaspinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        criteriaspinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        criteriaspinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        criteriaspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                criteriaspinnerStateChanged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HBondingCriteria.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(criteriaspinnerlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criteriaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriaspinnerlbl)
                    .addComponent(criteriaspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hbondcriteriapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hbondcriteriapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param evt 
     * 
     * This function saves the defined criteria after getting fields one by one
     */
    private void HbondsavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbondsavebtnActionPerformed
      int crt = Integer.parseInt(criteriaspinner.getValue().toString());
        if(numofcriteria < crt)
      {
        criteria.add(numofcriteria,new ArrayList<Object>(9));
        ArrayList<Double> dl= new ArrayList<Double>();
         for(Component cmp: this.hbondcriteriapanel.getComponents())
         {
             if(cmp instanceof JTextField)
             {
                 JTextField field = (JTextField) cmp;
                 if(field.getName() != null && field.getName().equals("Double"))
                     //criteria.get(numofcriteria).add(Double.parseDouble(field.getText()));
                     dl.add(Double.parseDouble(field.getText()));
                 else
                    criteria.get(numofcriteria).add(Integer.parseInt(field.getText()));      
             }
         }
        criteria.get(numofcriteria).addAll(dl);
        numofcriteria++;
        criteriaspinner.setModel(new SpinnerNumberModel(1,1,numofcriteria+1,1));
        criteriaspinner.setValue(numofcriteria+1);
        ((DefaultEditor) criteriaspinner.getEditor()).getTextField().setEditable(false);

        this.statuslbl.setText("saved criteria : "+numofcriteria);
         //criteriaspinnerlbl.setText("Saved Criteria:");
      }
        else{
                int count = 0;
            ArrayList<Double> dl= new ArrayList<Double>();
         for(Component cmp: this.hbondcriteriapanel.getComponents())
         {
             if(cmp instanceof JTextField)
             {
                 JTextField field = (JTextField) cmp;
                 if(field.getName() != null && field.getName().equals("Double"))
                     //criteria.get(numofcriteria).add(Double.parseDouble(field.getText()));
                     dl.add(Double.parseDouble(field.getText()));
                 else
                 {
                    criteria.get(crt-1).set(count,Integer.parseInt(field.getText()));
                    count++;
                 }
             }
             
         }
         for(int i=0;i<dl.size();i++)
         {
            criteria.get(crt-1).set(count,dl.get(i));
            count++;
         }
         
         this.statuslbl.setText("updated criteria : "+crt);
        }
     
         
    }//GEN-LAST:event_HbondsavebtnActionPerformed
   
    /**
     * 
     */
    private void setcriteriaspinner()
    {
        numofcriteria = criteria.size();
        criteriaspinner.setModel(new SpinnerNumberModel(1,1,numofcriteria+1,1));
        criteriaspinner.setValue(numofcriteria + 1);
       ((DefaultEditor) criteriaspinner.getEditor()).getTextField().setEditable(false);
       
        //this.statuslbl.setText("Add Criteria : "+numofcriteria);
        
    }
    // this fucntion sets the arraylist to the main function..
    private void closed()
    {
        this.main.NumHbondcriteria.setText(String.valueOf(criteria.size()));
        this.main.eData.numofcriteria = criteria.size();
        this.main.eData.hbondcriteria = this.criteria;
        this.setVisible(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        closed();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        closed();
    }//GEN-LAST:event_formWindowClosing
        // this function load the previous criterias in the arraylist
        //
    private void criteriaspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_criteriaspinnerStateChanged
        int crt = Integer.parseInt(criteriaspinner.getValue().toString());
        if(this.criteria.size() >= crt ) // numofcriteria
        {
            criteriaspinnerlbl.setText("Saved Criteria:");
            int count = 0;
            for(Component cmp: this.hbondcriteriapanel.getComponents())
            {
                if(cmp instanceof JTextField)
                {
                    JTextField field = (JTextField) cmp;
                    field.setText(criteria.get(crt-1).get(count).toString());
                    count++;
                 }
            }
            
            this.delCriteriabtn.setEnabled(true);
        }
        else
            setdefaultValue();
            
 
    }//GEN-LAST:event_criteriaspinnerStateChanged
    private void setdefaultValue() {
            this.delCriteriabtn.setEnabled(false);
            criteriaspinnerlbl.setText("Add Criteria:");
            int count = 0;
            for(Component cmp: this.hbondcriteriapanel.getComponents())
            {
                if(cmp instanceof JTextField)
                {
                    JTextField field = (JTextField) cmp;
                    field.setText(dval[count]);
                    count++;
                 }
            }
    }
    private void IntegerValidationOnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IntegerValidationOnFocusLost
        JTextField sf = (JTextField) evt.getSource();
        try{
            
            int d =  Integer.parseInt(sf.getText());
            
        }
        catch(Exception ex)
        {
            this.statuslbl.setText("Only number values are allowed");
            sf.requestFocus();
            sf.selectAll();
        }
    }//GEN-LAST:event_IntegerValidationOnFocusLost

    private void DoubleValidationOnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoubleValidationOnFocusLost
        JTextField sf = (JTextField) evt.getSource();
        try{
            
            Double d =  Double.parseDouble(sf.getText());
            
        }
        catch(Exception ex)
        {
            this.statuslbl.setText("Only number values are allowed/wrong seperator between number values");
            sf.requestFocus();
            sf.selectAll();
        }
    }//GEN-LAST:event_DoubleValidationOnFocusLost
    // this function deletes the specified criteria from the arraylist....
    private void delCriteriabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCriteriabtnActionPerformed
        
        int index = Integer.parseInt(this.criteriaspinner.getValue().toString());
        if(this.criteria.size() > 0) {
            this.criteria.remove(index - 1);
            setcriteriaspinner();
            this.statuslbl.setText("Deleted Criteria : "+index);
            setdefaultValue();
        }
        else {
             this.statuslbl.setText("Not saved yet...");
        }
        
    }//GEN-LAST:event_delCriteriabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HbondCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HbondCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HbondCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HbondCriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new HbondCriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hbondsavebtn;
    private javax.swing.JSpinner criteriaspinner;
    private javax.swing.JLabel criteriaspinnerlbl;
    private javax.swing.JButton delCriteriabtn;
    private javax.swing.JPanel hbondcriteriapanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel statuslbl;
    // End of variables declaration//GEN-END:variables
}
