/*
 * MatCompJPanel.java
 *
 * Created on 8. November 2006, 13:43
 */

package ms_newpars;

import java.awt.Component;
/*import java.awt.Dimension;*/
import java.util.*;
import javax.swing.AbstractCellEditor;
import javax.swing.JPanel;
import javax.swing.JTable;
/*import javax.swing.JTextField;*/
import javax.swing.table.*;



/**
 *
 * @author  berreth
 */
public class MatCompJPanel extends javax.swing.JFrame {
    
    /** Creates new form MatCompJPanel */
    public MatCompJPanel() {
        initComponents();
        
        EnsemblePanel curE = (EnsemblePanel) FileGenGUI.ensemblesTabbedPane.getSelectedComponent();
       

        jScrollPane1.setViewportView(jTable1);
        updateEtaXiTable();
    }     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eta / Xi");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PM_2", "1.0", null, null, null},
                {"PM_3", "1.0", "1.0", null, null},
                {"PM_4", "1.0", "1.0", "1.0", null},
                {"PM_5", null, null, null, null}
            },
            new String [] {
                "PM", "PM_1", "PM_2", "PM_3", "PM_4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        closeButton.setText("close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .add(closeButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /**
     *
     */
    public class etaxiTableCellRenderer extends JPanel implements TableCellRenderer {
    
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int col) {
            JPanel panel = null;
            if (col >= row+1) {
                EnsemblePanel curE = (EnsemblePanel) FileGenGUI.ensemblesTabbedPane.getSelectedComponent();

                PotentialModel rowPm = curE.eData.potModelList.get(row);
                PotentialModel colPm = curE.eData.potModelList.get(col);
                
                EtaXi cur = curE.eData.getEtaxi();
                
                while (cur.getNext()!=null){
                    if (cur.getPm1()==rowPm && cur.getPm2()==colPm)
                       break; 
                    cur = cur.getNext();
                }
                
                panel = new EtaXiJPanel(table, cur);

            } else {
                panel = null;
                //setBackground(200,200,200);
            }
            if (col==0){}

            return panel;
        }
 
    }
    
    /**
     *
     */
    public void updateEtaXiTable(){
                           
         EnsemblePanel curE = (EnsemblePanel) FileGenGUI.ensemblesTabbedPane.getSelectedComponent();
         
         int pmNum = curE.eData.potModelList.size();
         Object [][] TableObject = new Object[pmNum-1][pmNum-1];
         String [] Header = new String[pmNum];
         Header[0] = "Pot.Model";
         
         for (int i=1; i<pmNum;i++){
             PotentialModel pm = curE.eData.potModelList.get(i);
             Header[i] = pm.getName().toString();
             
         }
         for (int i=0; i<pmNum-1;i++){
             PotentialModel pm = curE.eData.potModelList.get(i);
             TableObject[i][0] = pm.getName().toString(); 
         }
                
         
         jTable1.setModel(new javax.swing.table.DefaultTableModel(TableObject,Header));
         this.jTable1.setDefaultRenderer(Object.class, new etaxiTableCellRenderer() );
         this.jTable1.setDefaultEditor(Object.class, new etaxiTableCellEditor() );
         this.jTable1.getColumnModel().getColumn(0).setCellRenderer( jTable1.getTableHeader().getDefaultRenderer() );
         this.jTable1.setRowHeight(75);
     }
     
    /**
     *
     */
    public class etaxiTableCellEditor extends AbstractCellEditor implements TableCellEditor {
        // This is the component that will handle the editing of the cell value
        //JComponent component = new JTextField();
        JPanel panel = null;
        // This method is called when a cell value is edited by the user.
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int col) {
            // 'value' is value contained in the cell located at (rowIndex, vColIndex)
            
            if (col >= row+1) {
                
                EnsemblePanel curE = (EnsemblePanel) FileGenGUI.ensemblesTabbedPane.getSelectedComponent();

                PotentialModel rowPm = curE.eData.potModelList.get(row);
                PotentialModel colPm = curE.eData.potModelList.get(col);
                
                EtaXi curEtaXi = curE.eData.getEtaxi();
                
                while (curEtaXi.getNext()!=null){
                    if (curEtaXi.getPm1()==rowPm && curEtaXi.getPm2()==colPm)
                       break; 
                    curEtaXi = curEtaXi.getNext();
                }
                table.setValueAt(curEtaXi,row,col);
                panel = new EtaXiJPanel(table, curEtaXi);
                return panel;
            } 
            else if (col == 0){
                return null;
            }
            else {
                return null;
            }
            /*if (isSelected) {
                // cell (and perhaps other cells) are selected
            }
    
            // Configure the component with the specified value
            ((JTextField)component).setText((String)value);
    
            // Return the configured component
            return component;*/
        }
    
        // This method is called when editing is completed.
        // It must return the new value to be stored in the cell.
        public Object getCellEditorValue() {
            
            return panel; //((JTextField)component).getText();
        }
    }
      
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
