/*
 * PmCopyDialog.java
 *
 * Created on 27. Maerz 2007, 18:55
 */
package ms_newpars;

/*import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;*/
import javax.swing.JTextField;


/**
 *
 * @author  berreth
 */
public class PmCopyDialog extends javax.swing.JDialog {
    
    /** Creates new form PmCopyDialog
     * @param parent
     * @param modal
     * @param curPm */
    public PmCopyDialog(FileGenGUI parent, boolean modal, PotentialModel curPm ) {
        super(parent, modal);
        this.main = parent;
        this.potmodel = curPm;
        initComponents();
        this.keepButton.requestFocusInWindow();
        this.pmLabel.setText(curPm.getName());
        this.filenameTextField.setText(curPm.getFileName());
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pmLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filenameLabel = new javax.swing.JLabel();
        filenameTextField = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        keepButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        allCheckBox = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Potential Model already exists");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getAccessibleContext().setAccessibleParent(null);
        pmLabel.setText("jLabel1");

        jLabel2.setText("already exists.");

        filenameLabel.setText("Filename:");

        filenameTextField.setText("jTextField1");
        filenameTextField.setNextFocusableComponent(saveButton);
        filenameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                filenameTextFieldFocusGained(evt);
            }
        });
        filenameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filenameTextFieldKeyTyped(evt);
            }
        });

        infoLabel.setText("Parameterfile will automatically be updated.");

        keepButton.setText("keep existing file");
        keepButton.setToolTipText("possible changes will be lost!");
        keepButton.setNextFocusableComponent(filenameTextField);
        keepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keepButtonActionPerformed(evt);
            }
        });

        saveButton.setText("overwrite");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        allCheckBox.setSelected(true);
        allCheckBox.setText("use this choice for all Potential Models");
        allCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        allCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        allCheckBox.setNextFocusableComponent(keepButton);

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cancelButton)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(pmLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(keepButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(filenameLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(filenameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, infoLabel)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, allCheckBox))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pmLabel)
                    .add(jLabel2))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(filenameLabel)
                    .add(filenameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(infoLabel)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveButton)
                    .add(keepButton))
                .add(11, 11, 11)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(allCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(cancelButton)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        main.allPmFileOption = true;
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!this.filenameTextField.getText().equals(this.potmodel.getFileName())){
            this.potmodel.setFileName(this.filenameTextField.getText());
            this.potmodel.setName(this.potmodel.getFileName().substring(0,this.potmodel.getFileName().length()-3));
        }
        if (this.allCheckBox.isSelected()){
            main.allPmFileOption = true;
        }
        this.main.pmFileOverwrite = true;
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void keepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keepButtonActionPerformed
        if (this.allCheckBox.isSelected()){
            main.allPmFileOption = true;
        }
        this.main.pmFileOverwrite = false;
        this.dispose();
    }//GEN-LAST:event_keepButtonActionPerformed

    private void filenameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filenameTextFieldFocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_filenameTextFieldFocusGained

    private void filenameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filenameTextFieldKeyTyped
        if (this.filenameTextField.getText().equals(this.potmodel.getFileName())){
            this.saveButton.setText("overwrite");
            //this.allCheckBox.setSelected(true);
        } else {
            this.saveButton.setText("save as...");
            this.allCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_filenameTextFieldKeyTyped
    
    private FileGenGUI main;
    private PotentialModel potmodel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JTextField filenameTextField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton keepButton;
    private javax.swing.JLabel pmLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    
}
