/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ms_newpars;

import java.awt.Color;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;

/**
 *
 * @author Syed ahsan ali
 */
public class ViewFiles extends javax.swing.JFrame {

    /**
     * Creates new form ViewFiles
     * @param path
     */
    public ViewFiles(String path) {
        initComponents();
        
        filetextarea.setEditable(false);
        setTitle(path);
        if(path.equals("Help"))
        {
            ReadHelpFile();
        }
        else
        {
            readfile(path);
        }
        
    }
    private void readfile(String fileName)
    {
        File inputFile = new File(fileName);
	BufferedReader inputStream;
	StringBuffer fileInString = new StringBuffer();
	String line;
	//int counter = 0;
	try {
	    inputStream = new BufferedReader(new FileReader(inputFile));
	    while((line = inputStream.readLine()) != null) {
		fileInString.append(line + "\n");
	    }
	} catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
	    ex.printStackTrace();
	}
        
	filetextarea.setText(fileInString.toString());
        
    }
    private void ReadHelpFile()
    {
        
	StringBuffer fileInString = new StringBuffer();
	String line;
	
	try {
            
            InputStream in = getClass().getResourceAsStream("/resources/MS2Par_Hilfe.txt"); 
            BufferedReader inputStream = new BufferedReader(new InputStreamReader(in));
	    while((line = inputStream.readLine()) != null) {
		fileInString.append(line + "\n");
	    }
	} catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
	    ex.printStackTrace();
	}
	
        filetextarea.setText(fileInString.toString());
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbtn = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        textareapane = new javax.swing.JScrollPane();
        filetextarea = new javax.swing.JTextArea();

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        textareapane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        filetextarea.setColumns(20);
        filetextarea.setRows(5);
        textareapane.setViewportView(filetextarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textareapane, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchtxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textareapane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
//        String searchWord = searchtxt.getText();
//        Highlighter.HighlightPainter painter =new DefaultHighlighter.DefaultHighlightPainter( Color.cyan );
//        String text = filetextarea.getText();
//        
//        filetextarea.getHighlighter().removeAllHighlights();
//        
//int offset = text.indexOf(searchWord);
//int length = searchWord.length();
//
//while ( offset != -1)
//{
//    try
//    {
//        filetextarea.getHighlighter().addHighlight(offset, offset + length, painter);
//        offset = text.indexOf(searchWord, offset+1);
//    }
//    catch(Exception ble) { System.out.println(ble); }
//}
        int pos = 0;
        String find = searchtxt.getText().toLowerCase();
                    // Focus the text area, otherwise the highlighting won't show up
                    filetextarea.requestFocusInWindow();
                    // Make sure we have a valid search term
                    if (find != null && find.length() > 0) {
                        Document document = filetextarea.getDocument();
                        int findLength = find.length();
                        try {
                            boolean found = false;
                            // Rest the search position if we're at the end of the document
                            if (pos + findLength > document.getLength()) {
                                pos = 0;
                            }
                            // While we haven't reached the end...
                            // "<=" Correction
                            while (pos + findLength <= document.getLength()) {
                                // Extract the text from teh docuemnt
                                String match = document.getText(pos, findLength).toLowerCase();
                                // Check to see if it matches or request
                                if (match.equals(find)) {
                                    found = true;
                                    break;
                                }
                                pos++;
                            }

                            // Did we find something...
                            if (found) {
                                // Get the rectangle of the where the text would be visible...
                                Rectangle viewRect = filetextarea.modelToView(pos);
                                // Scroll to make the rectangle visible
                                filetextarea.scrollRectToVisible(viewRect);
                                // Highlight the text
                                filetextarea.setCaretPosition(pos + findLength);
                                filetextarea.moveCaretPosition(pos);
                                // Move the search position beyond the current match
                                pos += findLength;
                            }

                        } catch (Exception exp) {
                            exp.printStackTrace();
                        }

                    }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ViewFiles().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea filetextarea;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JScrollPane textareapane;
    // End of variables declaration//GEN-END:variables
}
