/*
 * ChemPotMethodJFrame.java
 *
 * Created on 2. Mai 2007, 16:37
 */

package inputfilegen;


import java.io.*;

//import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextArea;

/**
 *
 * @author  berreth
 */
public class ChemPotMethodJFrame extends javax.swing.JFrame {
    
    /** Creates new form ChemPotMethodJFrame */
    public ChemPotMethodJFrame(PotentialModel curPm) {
        initComponents();
        this.weightFactorsTextField.setVisible(false);
        this.jScrollPane1.setVisible(false);
        
        this.pm = curPm;
        this.potModelName.setText(this.pm.getName());
        this.chemPotMethodTypeComboBox.setSelectedItem(this.pm.getChemPotMethod());
        this.nTestTextField.setText(String.valueOf(this.pm.getNTest()));
        this.weightFactorsType.setSelectedItem(this.pm.getWeightFactorsType());
        this.weightFactorsTextField.setText(this.pm.getWeightFactors());
    }
    
    public int validateInputInt(String str){
        int ret = 0;
        if (str.length() > 0) {
            try {
                ret = Integer.parseInt(str);
            } catch (Exception e){
                JOptionPane.showMessageDialog(new JFrame(), "The number you entered is not a valid number.");
            }
        }
        
        return ret;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        potModelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chemPotMethodTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nTestTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weightFactorsTextField = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        weightFactorsType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chemical Potential Method");

        jLabel1.setText("for Potential Model:");

        potModelName.setText("pmLabel");

        jLabel2.setText("Chemical Potential Method");

        chemPotMethodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "Widom", "GradIns" }));
        chemPotMethodTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemPotMethodTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("nTest");
        jLabel3.setEnabled(false);

        nTestTextField.setText("0");
        nTestTextField.setEnabled(false);

        jLabel4.setText("WeightFactors");
        jLabel4.setEnabled(false);

        weightFactorsTextField.setColumns(20);
        weightFactorsTextField.setRows(5);
        jScrollPane1.setViewportView(weightFactorsTextField);

        closeButton.setText("save");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        weightFactorsType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "Guess", "OptSet" }));
        weightFactorsType.setEnabled(false);
        weightFactorsType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightFactorsTypeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(potModelName))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(chemPotMethodTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(weightFactorsType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nTestTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(277, Short.MAX_VALUE)
                        .add(closeButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(112, 112, 112)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(potModelName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(chemPotMethodTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nTestTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(weightFactorsType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightFactorsTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightFactorsTypeActionPerformed
        textFieldVisible();
    }//GEN-LAST:event_weightFactorsTypeActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.pm.setChemPotMethod(this.chemPotMethodTypeComboBox.getSelectedItem().toString());
        this.pm.setNTest(this.validateInputInt(this.nTestTextField.getText()));
        this.pm.setWeightFactorsType(this.weightFactorsType.getSelectedItem().toString());
        this.pm.setWeightFactors(this.weightFactorsTextField.getText().trim());
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    
    private void chemPotMethodTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemPotMethodTypeComboBoxActionPerformed
        if(this.chemPotMethodTypeComboBox.getSelectedItem().equals("GradIns")){
            this.jLabel3.setVisible(false);
            this.nTestTextField.setVisible(false);
            this.jLabel4.setVisible(true);
            this.jLabel4.setEnabled(true);
            this.weightFactorsType.setVisible(true);
            this.weightFactorsType.setEnabled(true);        
            textFieldVisible(); 
        } else if (this.chemPotMethodTypeComboBox.getSelectedItem().equals("Widom")) {
            this.jLabel3.setVisible(true);
            this.jLabel3.setEnabled(true);
            this.nTestTextField.setVisible(true);
            this.nTestTextField.setEnabled(true);
            this.jLabel4.setVisible(false);
            this.weightFactorsType.setVisible(false);
            textFieldVisible();
        } else {
            this.jLabel3.setVisible(false);
            this.nTestTextField.setVisible(false);
            this.jLabel4.setVisible(false);
            this.weightFactorsType.setVisible(false);
            textFieldVisible();    
        }
    }//GEN-LAST:event_chemPotMethodTypeComboBoxActionPerformed

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
            JTextField jtf = (JTextField) evt.getSource();
            jtf.selectAll();
}//GEN-LAST:event_focusGained

    private void focusGainedArea(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedArea
            JTextArea jtf = (JTextArea) evt.getSource();
            jtf.selectAll();
    }//GEN-LAST:event_focusGainedArea
    
    
    private void textFieldVisible(){
        if (this.weightFactorsType.getSelectedItem().equals("Auto") && this.chemPotMethodTypeComboBox.getSelectedItem().equals("GradIns")){
            this.weightFactorsTextField.setVisible(true);
            this.weightFactorsTextField.setEnabled(true);
            this.jScrollPane1.setVisible(true);
            
            
            int NFluct = readNFluct(this.pm.getFile());
            
            if (NFluct != 0){
                int n = 0;
                int factor = 1;
                this.weightFactorsTextField.setText("");
                do{                    
                    if (n == 1){
                        factor = 4;
                    }
                    else if (n == 2){                        
                        factor = 16;
                    }
                    else if (n == 3){
                        factor = 20;
                    }
                    else if (n > 3){
                        factor = factor + 20;
                    }else {}   
                
                    String str = String.valueOf(factor);
                    this.weightFactorsTextField.append(str + "\n");
                
                    n++;
                
                }while (n < NFluct); 
            }   
        }else {
            
            this.weightFactorsTextField.setVisible(true);
            this.weightFactorsTextField.setEnabled(false);
            this.jScrollPane1.setVisible(true);
        } 
    }
    
   private int readNFluct(File pmFile){

        String adr = pmFile.getPath();
        int NFluct = 0;

        try {
            FileInputStream fis = new FileInputStream(adr);
            BufferedReader buff = new BufferedReader (new InputStreamReader(fis));
            try{
                String line;
                String[] words;
                while ((line = buff.readLine()) != null){
                    if (line.indexOf("NFluct") != -1){
                        words = line.split("=");
                        words[0] = treatment(words[0]);
                        if(words[0].equals("NFluct")){
                            words[1]= treatment(words[1]);
                            if (!words[1].equals("0")){
                                
                                NFluct = Integer.parseInt(words[1]);
                            }else{
                                JOptionPane.showMessageDialog(new JFrame(), "Token error or \n No given Value of NFluct");
                            }
                        }else{
                            JOptionPane.showMessageDialog(new JFrame(), "Token error when writting NFluct in pmFile"); 
                        }
                    }
                }
                if (NFluct == 0){
                    JOptionPane.showMessageDialog(new JFrame(), "Change Method \n Auto could not run");                    
                }  
            } finally{
                buff.close();               
            }
        }catch(IOException ioe){
            JOptionPane.showMessageDialog(new JFrame(), "Error--" + ioe.toString());
        }  
        return NFluct;
    }
   
   private String treatment(String str){
       StringTokenizer stk = new StringTokenizer(str, " ");
       String str1 = new String();
       while(stk.hasMoreTokens()){
           str = String.valueOf(stk.nextToken());
           if (!str.equals(" ")){
               str1 = str;
               if(str1.charAt(0) == ' '|| str1.charAt(0)=='\t')
                   str1 = "0";           
           }else{
               str1 = "0";
           }
       }
       
       return str1;
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox chemPotMethodTypeComboBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nTestTextField;
    private javax.swing.JLabel potModelName;
    private javax.swing.JTextArea weightFactorsTextField;
    private javax.swing.JComboBox weightFactorsType;
    // End of variables declaration//GEN-END:variables
    private PotentialModel pm;

    //private Ensemble eData;
}
