/*
 * EnsemblePanel.java
 *
 * Created on 4. November 2006, 15:29
 */

package inputfilegen;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

import java.io.File;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.*;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.filechooser.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
//import java.lang.Math;


/**
 *
 * @author  Christian Berreth
 */
public class EnsemblePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form EnsemblePanel
     */
    public EnsemblePanel(FileGenGUI parent) {
        initComponents();
   
        eData = new Ensemble();
        this.main = parent;
        
        this.eData.potModelList = new LinkedList<PotentialModel>();
        updateEnsemblePanel();
        
    }

    void optPressureChanged() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    

 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ensemblePanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        temperatureunitComboBox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        pressureTextField = new javax.swing.JTextField();
        pressureunitComboBox = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        densityTextField = new javax.swing.JTextField();
        densityunitComboBox = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        pistonmassTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        particlesTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        numberofcomponentsLabel = new javax.swing.JLabel();
        potmodeladdButton = new javax.swing.JButton();
        potmodelremoveButton = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        potmodelgeButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cutoffTextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        epsilonTextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cutoffljTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        cutoffddTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cutoffdqTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        cutoffqqTextField = new javax.swing.JTextField();
        potmodeltablelistScrollPane = new javax.swing.JScrollPane();
        potmodelTable = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        etaxiButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vapDensityTextField = new javax.swing.JTextField();
        calcMaxCutoff = new javax.swing.JButton();
        editPmFile = new javax.swing.JButton();
        chemPotMethodjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        corrLengthCFTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resFreqCFTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spanFunCFTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        viewFunCFTextField = new javax.swing.JTextField();
        vapdensityunitComboBox = new javax.swing.JComboBox();
        pistonmassunitComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        optPressureComboBox = new javax.swing.JComboBox();
        ensemblesgeButton = new javax.swing.JButton();

        jLabel22.setText("Temperature");

        temperatureTextField.setText("jTextField12");
        temperatureTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                temperatureTextFieldFocusLost(evt);
            }
        });

        temperatureunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "K", "°C" }));

        jLabel23.setText("Pressure");
        jLabel23.setEnabled(false);

        pressureTextField.setText("jTextField13");
        pressureTextField.setEnabled(false);
        pressureTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pressureTextFieldFocusLost(evt);
            }
        });

        pressureunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MPa", "bar" }));
        pressureunitComboBox.setEnabled(false);

        jLabel25.setText("Density");

        densityTextField.setText("jTextField14");
        densityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                densityTextFieldFocusLost(evt);
            }
        });

        densityunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mol / l" }));

        jLabel27.setText("Piston mass");
        jLabel27.setEnabled(false);

        pistonmassTextField.setText("jTextField15");
        pistonmassTextField.setEnabled(false);
        pistonmassTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pistonmassTextFieldFocusLost(evt);
            }
        });

        jLabel28.setText("Number of particles");

        particlesTextField.setText("jTextField16");
        particlesTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                particlesTextFieldFocusLost(evt);
            }
        });

        jLabel30.setText("Number of components:");

        numberofcomponentsLabel.setText("n");

        potmodeladdButton.setText("add");
        potmodeladdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodeladdButtonActionPerformed(evt);
            }
        });

        potmodelremoveButton.setText("remove");
        potmodelremoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodelremoveButtonActionPerformed(evt);
            }
        });

        jLabel33.setText("2nd Component:");

        potmodelgeButton.setText("GE-Parameter");
        potmodelgeButton.setEnabled(false);
        potmodelgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potmodelgeButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("Cutoff");

        cutoffTextField.setText("jTextField22");
        cutoffTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffTextFieldFocusLost(evt);
            }
        });

        jLabel40.setText("ε");

        epsilonTextField.setText("1.0E10");
        epsilonTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                epsilonTextFieldFocusLost(evt);
            }
        });

        jLabel36.setText("LJ");
        jLabel36.setEnabled(false);
        jLabel36.setVerifyInputWhenFocusTarget(false);

        cutoffljTextField.setText("jTextField23");
        cutoffljTextField.setEnabled(false);
        cutoffljTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffljTextFieldFocusLost(evt);
            }
        });

        jLabel37.setText("DD");
        jLabel37.setEnabled(false);

        cutoffddTextField.setText("jTextField24");
        cutoffddTextField.setEnabled(false);
        cutoffddTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffddTextFieldFocusLost(evt);
            }
        });

        jLabel38.setText("DQ");
        jLabel38.setEnabled(false);

        cutoffdqTextField.setText("jTextField25");
        cutoffdqTextField.setEnabled(false);
        cutoffdqTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffdqTextFieldFocusLost(evt);
            }
        });

        jLabel39.setText("QQ");
        jLabel39.setEnabled(false);

        cutoffqqTextField.setText("jTextField26");
        cutoffqqTextField.setEnabled(false);
        cutoffqqTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutoffqqTextFieldFocusLost(evt);
            }
        });

        potmodeltablelistScrollPane.setPreferredSize(new java.awt.Dimension(453, 353));

        potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Potential Model", "Mole Fract."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        potmodelTable.setSurrendersFocusOnKeystroke(true);
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        potmodelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potmodelTableMouseClicked(evt);
            }
        });
        potmodeltablelistScrollPane.setViewportView(potmodelTable);

        jLabel26.setText("reduced");

        jLabel31.setText("reduced");

        jLabel32.setText("reduced");

        etaxiButton.setText("Eta & Xi");
        etaxiButton.setEnabled(false);
        etaxiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaxiButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("VapDensity");

        vapDensityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vapDensityTextFieldFocusLost(evt);
            }
        });

        calcMaxCutoff.setText("calc max Cutoff");
        calcMaxCutoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcMaxCutoffActionPerformed(evt);
            }
        });

        editPmFile.setText("edit Model");
        editPmFile.setEnabled(false);
        editPmFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPmFileActionPerformed(evt);
            }
        });

        chemPotMethodjButton.setText("ChemPotMethod");
        chemPotMethodjButton.setEnabled(false);
        chemPotMethodjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemPotMethodjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Corrlength");
        jLabel2.setEnabled(false);

        corrLengthCFTextField.setText("10000");
        corrLengthCFTextField.setEnabled(false);
        corrLengthCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                corrLengthCFTextFieldFocusLost(evt);
            }
        });

        jLabel3.setText("ResFreqCF");
        jLabel3.setEnabled(false);

        resFreqCFTextField.setText("5");
        resFreqCFTextField.setEnabled(false);
        resFreqCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resFreqCFTextFieldFocusLost(evt);
            }
        });

        jLabel4.setText("SpanCorrFun");
        jLabel4.setEnabled(false);

        spanFunCFTextField.setText("300");
        spanFunCFTextField.setEnabled(false);
        spanFunCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spanFunCFTextFieldFocusLost(evt);
            }
        });

        jLabel5.setText("ViewCorrFun");
        jLabel5.setEnabled(false);

        viewFunCFTextField.setText("100");
        viewFunCFTextField.setEnabled(false);
        viewFunCFTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnsemblePanel.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                viewFunCFTextFieldFocusLost(evt);
            }
        });

        vapdensityunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mol / l" }));

        pistonmassunitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "u / m^4" }));

        jLabel6.setText("reduced");

        jLabel7.setText("reduced");

        jLabel8.setText("OptPressure");
        jLabel8.setEnabled(false);

        optPressureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        optPressureComboBox.setEnabled(false);
        optPressureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optPressureComboBoxActionPerformed(evt);
            }
        });

        ensemblesgeButton.setText("GE-Parameter");
        ensemblesgeButton.setEnabled(false);
        ensemblesgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensemblesgeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout ensemblePanelLayout = new org.jdesktop.layout.GroupLayout(ensemblePanel);
        ensemblePanel.setLayout(ensemblePanelLayout);
        ensemblePanelLayout.setHorizontalGroup(
            ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ensemblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel22)
                                            .add(jLabel23)
                                            .add(jLabel8)
                                            .add(jLabel25))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(optPressureComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(pressureTextField, 0, 0, Short.MAX_VALUE)
                                            .add(densityTextField)
                                            .add(temperatureTextField)
                                            .add(vapDensityTextField)
                                            .add(pistonmassTextField)))
                                    .add(jLabel1)
                                    .add(jLabel27)
                                    .add(jLabel28)
                                    .add(jLabel30)
                                    .add(potmodeltablelistScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(pistonmassunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(vapdensityunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(densityunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(pressureunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(temperatureunitComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel26)
                                            .add(jLabel7)
                                            .add(jLabel6)
                                            .add(jLabel32)
                                            .add(jLabel31)))
                                    .add(jLabel33)
                                    .add(editPmFile)
                                    .add(etaxiButton)
                                    .add(chemPotMethodjButton)
                                    .add(potmodelgeButton)
                                    .add(numberofcomponentsLabel)
                                    .add(particlesTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(ensemblesgeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .add(24, 24, 24))
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(potmodeladdButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(potmodelremoveButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(calcMaxCutoff))
                            .add(ensemblePanelLayout.createSequentialGroup()
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel24)
                                            .add(ensemblePanelLayout.createSequentialGroup()
                                                .add(28, 28, 28)
                                                .add(jLabel40)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(epsilonTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .add(cutoffTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel36)
                                            .add(jLabel37)))
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(jLabel3)
                                        .add(15, 15, 15)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, corrLengthCFTextField)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, resFreqCFTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                                .add(14, 14, 14)
                                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cutoffljTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cutoffddTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel38)
                                            .add(jLabel39))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cutoffdqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cutoffqqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(ensemblePanelLayout.createSequentialGroup()
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel4)
                                            .add(jLabel5))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(spanFunCFTextField)
                                            .add(viewFunCFTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
                                .add(170, 170, 170)))
                        .add(53, 53, 53))
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addContainerGap(507, Short.MAX_VALUE))))
        );
        ensemblePanelLayout.setVerticalGroup(
            ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ensemblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(temperatureTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel26)
                    .add(temperatureunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ensemblesgeButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(pressureTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel31)
                    .add(pressureunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(densityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel32)
                    .add(densityunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel25))
                .add(10, 10, 10)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(vapDensityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(vapdensityunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jLabel27))
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(pistonmassTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(pistonmassunitComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(optPressureComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel28)
                    .add(particlesTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel30)
                    .add(numberofcomponentsLabel))
                .add(25, 25, 25)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ensemblePanelLayout.createSequentialGroup()
                        .add(jLabel33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(editPmFile)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(etaxiButton)
                        .add(12, 12, 12)
                        .add(chemPotMethodjButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(potmodelgeButton))
                    .add(potmodeltablelistScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(potmodeladdButton)
                    .add(potmodelremoveButton)
                    .add(calcMaxCutoff))
                .add(18, 18, 18)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel24)
                    .add(cutoffljTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel38)
                    .add(cutoffdqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel36)
                    .add(cutoffTextField))
                .add(10, 10, 10)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cutoffddTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel39)
                    .add(cutoffqqTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel40)
                    .add(jLabel37)
                    .add(epsilonTextField))
                .add(18, 18, 18)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel4)
                    .add(spanFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(corrLengthCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ensemblePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel3)
                        .add(jLabel5)
                        .add(resFreqCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(viewFunCFTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(59, 59, 59))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ensemblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(ensemblePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
   

    private void chemPotMethodjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemPotMethodjButtonActionPerformed
        PotentialModel curPm = this.eData.potModelList.get(this.potmodelTable.getSelectedRow());
        new ChemPotMethodJFrame(curPm).setVisible(true);
    }//GEN-LAST:event_chemPotMethodjButtonActionPerformed
    
    
    private void editPmFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPmFileActionPerformed
        PotentialModel curPm = this.eData.potModelList.get(this.potmodelTable.getSelectedRow());
        new PmEditor(curPm).setVisible(true);
    }//GEN-LAST:event_editPmFileActionPerformed
    
    private void calcMaxCutoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcMaxCutoffActionPerformed

        calcMaxCutoff();

    }//GEN-LAST:event_calcMaxCutoffActionPerformed
    
    private void vapDensityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vapDensityTextFieldFocusLost
        if (this.vapDensityTextField.getText().length() > 0){
            this.eData.setVapDensity(this.main.validateInputDouble(this.vapDensityTextField.getText()));
            this.vapDensityTextField.setText(String.valueOf(this.eData.getVapDensity()));
        } else {
            //this.eData.setVapDensity(null);
        }
    }//GEN-LAST:event_vapDensityTextFieldFocusLost
    
    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_focusGained
    
    private void epsilonTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_epsilonTextFieldFocusLost
        this.eData.setEps(this.main.validateInputDouble(this.epsilonTextField.getText()));
        this.epsilonTextField.setText(String.valueOf(this.eData.getEps()));
    }//GEN-LAST:event_epsilonTextFieldFocusLost
    
    private void cutoffqqTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffqqTextFieldFocusLost
        this.eData.setCutOffQQ(this.main.validateInputDouble(this.cutoffqqTextField.getText()));
        this.cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
    }//GEN-LAST:event_cutoffqqTextFieldFocusLost
    
    private void cutoffdqTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffdqTextFieldFocusLost
        this.eData.setCutOffDQ(this.main.validateInputDouble(this.cutoffdqTextField.getText()));
        this.cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
    }//GEN-LAST:event_cutoffdqTextFieldFocusLost
    
    private void cutoffddTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffddTextFieldFocusLost
        this.eData.setCutOffDD(this.main.validateInputDouble(this.cutoffddTextField.getText()));
        this.cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
    }//GEN-LAST:event_cutoffddTextFieldFocusLost
    
    private void cutoffljTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffljTextFieldFocusLost
        this.eData.setCutOffLJ(this.main.validateInputDouble(this.cutoffljTextField.getText()));
        this.cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
    }//GEN-LAST:event_cutoffljTextFieldFocusLost
    
    private void cutoffTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutoffTextFieldFocusLost
        this.eData.setCutOff(this.main.validateInputDouble(this.cutoffTextField.getText()));
        this.cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
    }//GEN-LAST:event_cutoffTextFieldFocusLost
        
    private void particlesTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_particlesTextFieldFocusLost
        this.eData.setNPart(this.main.validateInputInt(this.particlesTextField.getText()));
        this.particlesTextField.setText(String.valueOf(this.eData.getNPart()));
    }//GEN-LAST:event_particlesTextFieldFocusLost
    
    private void pistonmassTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pistonmassTextFieldFocusLost
        this.eData.setPistonMass(this.main.validateInputDouble(this.pistonmassTextField.getText()));
        this.pistonmassTextField.setText(String.valueOf(this.eData.getPistonMass()));
    }//GEN-LAST:event_pistonmassTextFieldFocusLost
    
    private void densityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_densityTextFieldFocusLost
        this.eData.setDensity(this.main.validateInputDouble(this.densityTextField.getText()));
        this.densityTextField.setText(String.valueOf(this.eData.getDensity()));
    }//GEN-LAST:event_densityTextFieldFocusLost
    
    private void pressureTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pressureTextFieldFocusLost
        this.eData.setPressure(this.main.validateInputDouble(this.pressureTextField.getText()));
        this.pressureTextField.setText(String.valueOf(this.eData.getPressure()));
    }//GEN-LAST:event_pressureTextFieldFocusLost
    
    private void temperatureTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temperatureTextFieldFocusLost
        this.eData.setTemperature(this.main.validateInputDouble(this.temperatureTextField.getText()));
        this.temperatureTextField.setText(String.valueOf(this.eData.getTemperature()));
        this.main.saveFile = null;
    }//GEN-LAST:event_temperatureTextFieldFocusLost
    
    
    
    
/*
         Double newMolFrac = Double.valueOf(this.potmodelTable.getValueAt(0,this.potmodelTable.getSelectedRow()).toString()).doubleValue();
        this.eData.potModelList.get(this.potmodelTable.getSelectedRow()).setMolarFrac(newMolFrac);
 */
    
    private void potmodelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potmodelTableMouseClicked
        
        updatePmButtons();
        
    }//GEN-LAST:event_potmodelTableMouseClicked
    
    private void potmodelgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodelgeButtonActionPerformed
        
        if (this.eData.potModelList.size() > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            if (row >= 0){
                
                PotentialModel curPm = this.eData.potModelList.get(row);
                
                //PotentialModel curPm = this.potmodelTable.getValueAt(0,row);
                
                new GePmJFrame(curPm).setVisible(true);
                
            }
        }
        
    }//GEN-LAST:event_potmodelgeButtonActionPerformed
    
    private void potmodelremoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodelremoveButtonActionPerformed
        
        if (this.eData.potModelList.size() > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            
            
            if (row >= 0){
                PotentialModel curPm = this.eData.potModelList.get(row);
                //PotentialModel curPm = this.potmodelTable.getValueAt(0,row);
                int ret;
                ret = JOptionPane.showConfirmDialog(new JFrame(), "Are you sure, you want to remove this Potential Model ?","Delete?", 0);
                if (ret==0){
                    //this.eData.potModelList.remove(row);
                    removeEtaXi(curPm);
                    this.eData.potModelList.remove(curPm);
                    
                    updatePmTable();
                } else {}
                
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "No Potential Model selected");
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "No Potential Model");
        }
        updatePmButtons();
        
    }//GEN-LAST:event_potmodelremoveButtonActionPerformed
    
    private void ensemblesgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensemblesgeButtonActionPerformed
        JFrame GeEnsembleFrame = (new GeEnsembleJFrame(this.eData));
        GeEnsembleFrame.setVisible(true);
        
    }//GEN-LAST:event_ensemblesgeButtonActionPerformed
    
    private void etaxiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaxiButtonActionPerformed
        
        int pmSize = this.eData.potModelList.size();
        if (pmSize > 1 ) {
            
            MatCompJPanel etaXiPanel = new MatCompJPanel();
            
            if (pmSize > 7) {
                etaXiPanel.setSize(1000,700);
            } else {
                etaXiPanel.setSize(pmSize*100+200,pmSize*75+100);
            }
            
            etaXiPanel.setVisible(true);
            
        }
        
        
        
        
    }//GEN-LAST:event_etaxiButtonActionPerformed
    
    private void potmodeladdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potmodeladdButtonActionPerformed
        int PmTabRows;
        
        String pmdirpathSelected;
        File pmfileSelected;
        File pmdirSelected;
        File pmdirDefault = null;
        
        class pmFilter extends FileFilter {
            public String getDescription() {
                return "Only Potential Model Files";
            }
            
            public boolean accept(File f) {
                if (f == null)
                    return false;
                if (f.isDirectory())
                    return true;
                return f.getName().toLowerCase().endsWith(".pm");
            }
        }
        
        JFileChooser pmfileChooser = new JFileChooser();
        pmfileChooser.addChoosableFileFilter(new pmFilter());
        pmfileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        pmfileChooser.setCurrentDirectory(pmdirDefault);
        int returnVal = pmfileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            pmdirSelected = pmfileChooser.getCurrentDirectory();
            pmfileSelected = pmfileChooser.getSelectedFile();
            pmdirpathSelected = pmdirSelected.getAbsolutePath();
            
            double molfrac=1.0;
            
            if (this.eData.potModelList.size() > 0){
                
                Iterator pmIt = this.eData.potModelList.iterator();
                while (pmIt.hasNext()) {
                    PotentialModel pm = (PotentialModel)pmIt.next();
                    molfrac -= pm.getMolarFrac();
                }
            }
            
            molfrac = Math.round(molfrac*10.)/10.;
            double input = -1.0;
            while (input < 0.0 || input > 1.0) {
                try {
                    input = this.main.validateInputDouble(JOptionPane.showInputDialog("Mole Fraction:",molfrac));
                } catch(Exception e) {
                    break;
                }
            }
            molfrac = input;
            
            if (input >= 0.0 && input <= 1.0) {
                PotentialModel pm = new PotentialModel(pmfileSelected, molfrac);
                this.eData.potModelList.add(pm);
                
                if (this.eData.potModelList.size() > 1){
                    addEtaXi(pm);
                    
                }
            }
            
            updatePmTable();
            this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
            updatePmButtons();
            
        }
    }//GEN-LAST:event_potmodeladdButtonActionPerformed

    private void corrLengthCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_corrLengthCFTextFieldFocusLost
        this.eData.setcorrLengthCF(this.main.validateInputInt(this.corrLengthCFTextField.getText()));
        this.corrLengthCFTextField.setText(String.valueOf(this.eData.getcorrLengthCF()));
    }//GEN-LAST:event_corrLengthCFTextFieldFocusLost

    private void resFreqCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resFreqCFTextFieldFocusLost
        this.eData.setresFreqCF(this.main.validateInputInt(this.resFreqCFTextField.getText()));
        this.resFreqCFTextField.setText(String.valueOf(this.eData.getresFreqCF()));
    }//GEN-LAST:event_resFreqCFTextFieldFocusLost

    private void spanFunCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spanFunCFTextFieldFocusLost
        this.eData.setspanFunCF(this.main.validateInputInt(this.spanFunCFTextField.getText()));
        this.spanFunCFTextField.setText(String.valueOf(this.eData.getspanFunCF()));
    }//GEN-LAST:event_spanFunCFTextFieldFocusLost

    private void viewFunCFTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_viewFunCFTextFieldFocusLost
        this.eData.setviewFunCF(this.main.validateInputInt(this.viewFunCFTextField.getText()));
        this.viewFunCFTextField.setText(String.valueOf(this.eData.getviewFunCF()));
    }//GEN-LAST:event_viewFunCFTextFieldFocusLost

    private void optPressureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optPressureComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_optPressureComboBoxActionPerformed
    
    public void addEtaXi(PotentialModel pm) {
        LinkedList pmList = this.eData.potModelList;
        
        /* Insert first EtaXi for 2nd Model */
        if (this.eData.getEtaxi() == null){
            this.eData.setEtaxi(new EtaXi((PotentialModel) pmList.get(0),pm));
            this.eData.setLast(this.eData.getEtaxi());
        } else {
            EtaXi cur = this.eData.getEtaxi();
            int i = 0;
            while (cur != this.eData.getLast()){
                // Insert EtaXi at row end 
                if (cur.getRowEnd()){
                    EtaXi newEtaXi = new EtaXi((PotentialModel) pmList.get(i),pm);
                    newEtaXi.setNext(cur.getNext());
                    cur.setNext(newEtaXi);
                    cur.setRowEnd(false);
                    cur = cur.getNext();
                    i++;
                }
                
                cur = cur.getNext();
            }
            cur.setRowEnd(false);
            /* Add EtaXi after last Element*/
            cur.setNext(new EtaXi((PotentialModel) pmList.get(i),pm));
            this.eData.setLast(this.eData.getLast().getNext());
            i++;
            /* Add last EtaXi */
            this.eData.getLast().setNext(new EtaXi((PotentialModel) pmList.get(i),pm));
            this.eData.setLast(this.eData.getLast().getNext());
            
        }
    }
    
    private void removeEtaXi(PotentialModel pm){
        
        EtaXi cur = this.eData.getEtaxi();
        EtaXi prev = null;
        while(cur !=null){
            if (cur.getPm1()==pm || cur.getPm2()==pm){
                if (cur == this.eData.getEtaxi()){
                    this.eData.setEtaxi(cur.getNext());
                } else if (cur==this.eData.getLast()){
                    this.eData.setLast(prev);
                    prev.setNext(null);
                } else{
                    prev.setNext(cur.getNext());
                }
            }
            prev = cur;
            cur = cur.getNext();
        }
        
    }
    
    
    public void initPanel() {
        
        this.eData = new Ensemble();
        this.eData.potModelList = new LinkedList<PotentialModel>();
        
        updateEnsemblePanel();
        
    }
    
    public void updateEnsemblePanel() {
        
        temperatureTextField.setText(String.valueOf(this.eData.getTemperature()));
        pressureTextField.setText(String.valueOf(this.eData.getPressure()));
        densityTextField.setText(String.valueOf(this.eData.getDensity()));
        vapDensityTextField.setText(String.valueOf(this.eData.getVapDensity()));
        pistonmassTextField.setText(String.valueOf(this.eData.getPistonMass()));
        jLabel27.setEnabled(false);
        pistonmassTextField.setEnabled(false);
        pistonmassunitComboBox.setEnabled(false);
        particlesTextField.setText(String.valueOf(this.eData.getNPart()));
        
        cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
        cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
        cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
        cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
        cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
        epsilonTextField.setText(String.valueOf(this.eData.getEps()));

        resFreqCFTextField.setText(String.valueOf(this.eData.getresFreqCF()));
        corrLengthCFTextField.setText(String.valueOf(this.eData.getcorrLengthCF()));
        spanFunCFTextField.setText(String.valueOf(this.eData.getspanFunCF()));
        viewFunCFTextField.setText(String.valueOf(this.eData.getviewFunCF()));

        if (this.main.systemofunitsComboBox.getSelectedItem().toString().equals("SI")){
            
            jLabel26.setVisible(false);
            jLabel31.setVisible(false);
            jLabel32.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            
        } else {
            this.temperatureunitComboBox.setVisible(false);
            this.pressureunitComboBox.setVisible(false);
            this.densityunitComboBox.setVisible(false);
             
        }
        if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("GE")){
            this.ensemblesgeButton.setEnabled(true);
            
        }
        if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NPT")){
            this.pressureTextField.setEnabled(true);
            this.pressureunitComboBox.setEnabled(true);
            if (this.main.typeofsimulationComboBox.getSelectedItem().toString().equals("MD")){
                this.pistonmassTextField.setEnabled(true);
            }
            
        }
        
        updatePmTable();
        updatePmButtons();
    }
    
    private void initPmTable() {
        
        potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String [] {"Pot. Model", "Mole Fract."}
        )
        );
        
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        
        this.potmodelTable.getColumnModel().getColumn(0).setCellRenderer( this.potmodelTable.getTableHeader().getDefaultRenderer() );
        this.potmodelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    public void updatePmButtons(){
        int pmNum = this.eData.potModelList.size();
        if (pmNum > 0 ) {
            int row = this.potmodelTable.getSelectedRow();
            if (row >= 0){
                this.editPmFile.setEnabled(true);
                if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("GE")){
                    this.potmodelgeButton.setEnabled(true);
                    //this.potmodelgeButton.setVisible(true);
                    this.chemPotMethodjButton.setEnabled(false);
                    //this.chemPotMethodjButton.setVisible(false);
                } else{
                    this.potmodelgeButton.setEnabled(false);
                    //this.potmodelgeButton.setVisible(false);
                    this.chemPotMethodjButton.setEnabled(true);
                    //this.chemPotMethodjButton.setVisible(true);
                }
            } else {
                this.editPmFile.setEnabled(false);
                this.potmodelgeButton.setEnabled(false);
                this.chemPotMethodjButton.setEnabled(false);
            }
            if (this.eData.potModelList.size() > 1 ) {
                this.etaxiButton.setEnabled(true);
            } else{
                this.etaxiButton.setEnabled(false);
            }
        } else {
            this.etaxiButton.setEnabled(false);
            this.potmodelgeButton.setEnabled(false);
            this.chemPotMethodjButton.setEnabled(false);
            this.editPmFile.setEnabled(false);
        }
        
    }
    
    public void updatePmTable() {
        if (this.eData.potModelList.size() > 0){
            
            Object[][] pmObjArray = new Object [this.eData.potModelList.size()][2];
            
            for (int i=0; i < pmObjArray.length; i++) {
                
                PotentialModel curPm = this.eData.potModelList.get(i);
                
                pmObjArray[i][0] = curPm.getName();
                pmObjArray[i][1] = curPm.getMolarFrac();
            }
            potmodelTable.setModel(new javax.swing.table.DefaultTableModel(
                    (Object[][]) pmObjArray ,
                    new String [] {"Pot. Model", "Mole Fract."}
            )
            );
            
        } else {
            initPmTable();
        }
        this.potmodelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.potmodelTable.getColumnModel().getColumn(0).setCellEditor(new NoTableCellEditor());
        this.potmodelTable.getColumnModel().getColumn(1).setCellEditor(new pmTableCellEditor());
        this.potmodelTable.getColumnModel().getColumn(0).setCellRenderer( this.potmodelTable.getTableHeader().getDefaultRenderer() );
        this.numberofcomponentsLabel.setText(String.valueOf(this.potmodelTable.getRowCount()));
        
    }
    
    public class NoTableCellEditor extends AbstractCellEditor implements TableCellEditor {
        
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int rowIndex, int vColIndex) {
            return null;
        }
        
        public Object getCellEditorValue() {
            return null;
        }
    }
    
    public class pmTableCellEditor extends AbstractCellEditor implements TableCellEditor {
        
        JComponent component = new JTextField();
        
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int col) {
            
            ((JTextField)component).setText(String.valueOf(value));
            
            return component;
        }
        
        public Object getCellEditorValue() {
            EnsemblePanel curE = (EnsemblePanel) main.ensemblesTabbedPane.getSelectedComponent();
            PotentialModel pm = curE.eData.potModelList.get(curE.potmodelTable.getSelectedRow());
            double molfrac = Double.valueOf(((JTextField)component).getText());
            pm.setMolarFrac(molfrac);
            return ((JTextField)component).getText();
        }
        
    }
    
        private void calcMaxCutoff(){
        
            
        if (this.main.gData.getLengthUnit()==0.0)
            JOptionPane.showMessageDialog(new JFrame()," LenghtUnit = 0.0 ");
        else if (this.eData.getNPart()==0)
            JOptionPane.showMessageDialog(new JFrame()," NParticles = 0 ");
        else if (this.eData.getDensity()==0.0)
            JOptionPane.showMessageDialog(new JFrame()," Density = 0.0 ");
        else {
                
            double maxCutoff;
            double density = this.eData.getDensity();
            if ((this.main.systemofunitsComboBox.getSelectedItem().toString().equals("SI"))){
                density = (density*1E-27)*(6.022E23)*(Math.pow(this.main.gData.getLengthUnit(),3.));
      
            }
            maxCutoff = (this.eData.getNPart())/density;

            maxCutoff = 0.5 * Math.pow(maxCutoff, 1./3.) ;
            maxCutoff = Math.round(maxCutoff*100.)/100.;
 
                    
            if (this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NVE") ||this.main.typeofensembleComboBox.getSelectedItem().toString().equals("NVT")){
                    this.eData.setCutOff(maxCutoff);
                    
                    this.eData.setCutOffLJ(maxCutoff);
                    this.eData.setCutOffDD(maxCutoff);
                    this.eData.setCutOffDQ(maxCutoff);
                    this.eData.setCutOffQQ(maxCutoff);
                    if (this.main.cutofftypeComboBox.getSelectedItem().toString().equals("COM")){
                        
                        this.cutoffTextField.setText(String.valueOf(this.eData.getCutOff()));
                    }                     
                    else{
                        
                        this.cutoffljTextField.setText(String.valueOf(this.eData.getCutOffLJ()));
                        this.cutoffddTextField.setText(String.valueOf(this.eData.getCutOffDD()));
                        this.cutoffdqTextField.setText(String.valueOf(this.eData.getCutOffDQ()));
                        this.cutoffqqTextField.setText(String.valueOf(this.eData.getCutOffQQ()));
                    }                      
            }
            else{
                FileGenGUI parent2 = this.main;
                Ensemble parent1 = this.eData;          
                this.eData.setCutOff(maxCutoff);
               
                this.cutoffTextField.setEnabled(false);
                this.jLabel24.setEnabled(false);
                new changeMaxCutoffJFrame(parent1,this,parent2).setVisible(true);
           }
 
        }
        
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton calcMaxCutoff;
    public javax.swing.JButton chemPotMethodjButton;
    public javax.swing.JTextField corrLengthCFTextField;
    public javax.swing.JTextField cutoffTextField;
    public javax.swing.JTextField cutoffddTextField;
    public javax.swing.JTextField cutoffdqTextField;
    public javax.swing.JTextField cutoffljTextField;
    public javax.swing.JTextField cutoffqqTextField;
    public javax.swing.JTextField densityTextField;
    public javax.swing.JComboBox densityunitComboBox;
    private javax.swing.JButton editPmFile;
    public javax.swing.JPanel ensemblePanel;
    public javax.swing.JButton ensemblesgeButton;
    public javax.swing.JTextField epsilonTextField;
    private javax.swing.JButton etaxiButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel40;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel numberofcomponentsLabel;
    public javax.swing.JComboBox optPressureComboBox;
    public javax.swing.JTextField particlesTextField;
    public javax.swing.JTextField pistonmassTextField;
    public javax.swing.JComboBox pistonmassunitComboBox;
    public javax.swing.JTable potmodelTable;
    public javax.swing.JButton potmodeladdButton;
    public javax.swing.JButton potmodelgeButton;
    private javax.swing.JButton potmodelremoveButton;
    private javax.swing.JScrollPane potmodeltablelistScrollPane;
    public javax.swing.JTextField pressureTextField;
    public javax.swing.JComboBox pressureunitComboBox;
    public javax.swing.JTextField resFreqCFTextField;
    public javax.swing.JTextField spanFunCFTextField;
    public javax.swing.JTextField temperatureTextField;
    public javax.swing.JComboBox temperatureunitComboBox;
    public javax.swing.JTextField vapDensityTextField;
    public javax.swing.JComboBox vapdensityunitComboBox;
    public javax.swing.JTextField viewFunCFTextField;
    // End of variables declaration//GEN-END:variables
    
    public Ensemble eData;
    // public EnsemblePanel fData;
    private FileGenGUI main;
    
}
