/*
 * EtaXiJPanel.java
 *
 * Created on 29. Maerz 2007, 15:15
 */

package inputfilegen;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author  berreth
 */
public class EtaXiJPanel extends javax.swing.JPanel {
    
    /** Creates new form EtaXiJPanel */
    public EtaXiJPanel(JTable table, EtaXi curEtaxi) {
        initComponents();
        this.table = table;
        this.etaxi = curEtaxi;            
        this.etajTextField.setText(String.valueOf(etaxi.getEta()));
        this.xijTextField.setText(String.valueOf(etaxi.getXi()));
        this.etajTextField.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        etajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        xijTextField = new javax.swing.JTextField();

        jLabel1.setText("\u03b7");

        etajTextField.setText("jTextField1");
        etajTextField.setNextFocusableComponent(xijTextField);
        etajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                etajTextFieldFocusLost(evt);
            }
        });

        jLabel2.setText("\u03be");

        xijTextField.setText("jTextField2");
        xijTextField.setNextFocusableComponent(etajTextField);
        xijTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                xijTextFieldFocusLost(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etajTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(xijTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(etajTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(xijTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xijTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xijTextFieldFocusLost
        this.etaxi.setXi(this.validateInputDouble(this.xijTextField.getText()));
        //this.xijTextField.setText(String.valueOf(this.etaxi.getXi()));    
        this.table.repaint();
    }//GEN-LAST:event_xijTextFieldFocusLost

    private void etajTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_etajTextFieldFocusLost
        this.etaxi.setEta(this.validateInputDouble(this.etajTextField.getText()));
        //this.etajTextField.setText(String.valueOf(this.etaxi.getEta()));
        this.table.repaint();
    }//GEN-LAST:event_etajTextFieldFocusLost

    private void jTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFocusGained
        JTextField jtf = (JTextField) evt.getSource();
        jtf.selectAll();
    }//GEN-LAST:event_jTextFieldFocusGained
   
    private double validateInputDouble(String str){
        double ret = 1.0;
        if (str.length() > 0) {
            try {
                ret = Double.valueOf(str).doubleValue();
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "The number you entered is not a valid decimal number.");
            }
        }
        return ret;
    }
    private JTable table;
    private EtaXi etaxi = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etajTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField xijTextField;
    // End of variables declaration//GEN-END:variables
    
}
