/*
 * ShowFileFrame.java
 *
 * Created on 2. Juni 2006, 02:42
 *
 * Copyright (C) 2006, Anupam Srivastava
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

package ms2package;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 * Used to show the contents of a given file. This source code file is not meant
 * to be run seperately, but to be used in conjuction with other programs.
 * <P>Changelog:<BR>
 * 1.2 Added JFrame title<BR>
 * 1.1 Use FileReader class<BR>
 * </P>
 * @author Anupam Srivastava, 2006
 * @version 1.2 Sat, 18 Nov 2006 23:19:42 +0000
 */
public class ShowFileFrame extends javax.swing.JFrame {
    /**
     * Creates new form ShowFileFrame and displays no file.
     */
    public ShowFileFrame() {
	initComponents();
    }
    
    /**
     * Creates new form ShowFileFrame from a given file.
     *
     * @param fileName The path and name of the file.
     */
    public ShowFileFrame(String fileName) {
	initComponents();
        setTitle(fileName);
	resultTextArea.setText(readFile(fileName));
    }
    
    /**
     * This reads the file present as <CODE>fileName</CODE> into a String.
     * @param fileName The path and name of the file.
     * @return String
     */
    public String readFile(String fileName) {
	File inputFile = new File(fileName);
	BufferedReader inputStream;
	StringBuffer fileInString = new StringBuffer();
	String line;
	int counter = 0;
	try {
	    inputStream = new BufferedReader(new FileReader(inputFile));
	    while((line = inputStream.readLine()) != null) {
		fileInString.append(line + "\n");
	    }
	} catch (Exception ex) {
	    ex.printStackTrace();
	}
	return fileInString.toString();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        resultsScrollPane = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        dismissButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("<No File>");
        resultTextArea.setColumns(20);
        resultTextArea.setEditable(false);
        resultTextArea.setFont(new java.awt.Font("Monospaced", 0, 12));
        resultTextArea.setRows(5);
        resultTextArea.setText("No text to display.");
        resultTextArea.setDoubleBuffered(true);
        resultsScrollPane.setViewportView(resultTextArea);

        dismissButton.setText("Dismiss");
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, resultsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .add(dismissButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(resultsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dismissButton)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the window.
     * @param evt Action Event
     */
    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dismissButtonActionPerformed
    {//GEN-HEADEREND:event_dismissButtonActionPerformed
	setVisible(false);
	dispose();
    }//GEN-LAST:event_dismissButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dismissButton;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JScrollPane resultsScrollPane;
    // End of variables declaration//GEN-END:variables
}
