/*
 * ShowTableFrame.java
 *
 * Created on November 19, 2006, 2:28 AM
 *
 * Copyright (C) 2006, Anupam Srivastava
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

package ms_newcharts;

/**
 * Used to show a table. This source code file is not meant to be run
 * seperately, but to be used in conjuction with other programs.
 * @author Anupam Srivastava, 2006
 * @version 1.0
 */
public class ShowTableFrame extends javax.swing.JFrame {
    /**
     * Creates new form ShowTableFrame and displays an empty table in it.
     */
    public ShowTableFrame() {
        initComponents();
    }
    
    /**
     * Creates a new form ShowTableFrame from the given data to show the table.
     * 
     * @param data The data for the table.
     * @param title The header for the columns.
     */
    public ShowTableFrame(Object[][] data, String[] title) {
        initComponents();
        tableChartData.removeAll();
        tableChartData.setModel(new javax.swing.table.DefaultTableModel(data, title));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        tableChartData = new javax.swing.JTable();
        buttonDismiss = new javax.swing.JButton();

        setTitle("Data used in the chart");

        tableScrollPane.setDoubleBuffered(true);

        tableChartData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableChartData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableScrollPane.setViewportView(tableChartData);

        buttonDismiss.setText("Dismiss");
        buttonDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDismissActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonDismiss)
                    .add(tableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(tableScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonDismiss)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the window.
     * @param evt Action Event
     */
    private void buttonDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDismissActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonDismissActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDismiss;
    private javax.swing.JTable tableChartData;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
