/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ms2molecules;


import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Syed Ahsan Ali
 */
public class ms2molecules extends javax.swing.JFrame {

    /**
     * Creates new form ms2molecules
     */
    File OpenSelectedDir = null;
    String UserDirectory = null;
    String OperatingSystem = null;
    String javaver = null;
    File SavedFile = null;
    File Cdir = null;
    
    public ms2molecules() {
        initComponents();
        
        /* Get all the required system properties
         * sysdir : c:\windows\System32 etc
         * OperatingSystem : OS name
         * javaver : version of the java used by the system 32 or 64
         * OSarch : architecture of the OS 32 or 64
        */
        
            OperatingSystem = System.getProperty("os.name");
            UserDirectory = System.getProperty("user.dir");
            javaver = System.getProperty("sun.arch.data.model");
            String OSarch = System.getProperty("os.arch");
            
            /* 
                Print all the variables 
            */
            System.out.println("Java version : "+javaver);
            System.out.println("Os version : "+OSarch);
            System.out.println("OS name : "+OperatingSystem);
            System.out.println("User Directory : "+UserDirectory);
           
            /*
                If its the windows check if all the required dlls exists on the system 
                and copy them from the program folder by configuration function which then call batch file
                to get admin priviliges and copy files
            Note: No need to check it for Linux as tested dlls always appeared to exist
            */
            if(OperatingSystem.toLowerCase().contains("windows"))
            {   
                 String command = String.format("\""+UserDirectory+"\\bin\\windows\\config.bat\" %s",javaver);
                 System.out.println("command to run config : "+command);
            try {
                Runtime.getRuntime().exec(command);
            } catch (IOException ex) {
                Logger.getLogger(ms2molecules.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        browsetxt = new javax.swing.JTextField();
        browsebtn = new javax.swing.JButton();
        runbtn = new javax.swing.JButton();
        helpbtn = new javax.swing.JButton();
        viewcolorsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ms2molecules");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Choose File:");

        browsetxt.setEditable(false);

        browsebtn.setText("Browse");
        browsebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebtnActionPerformed(evt);
            }
        });

        runbtn.setText("Run");
        runbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runbtnActionPerformed(evt);
            }
        });

        helpbtn.setText("Help");
        helpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbtnActionPerformed(evt);
            }
        });

        viewcolorsbtn.setText("View Colors");
        viewcolorsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcolorsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(runbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(helpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewcolorsbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(browsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(browsebtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browsebtn)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runbtn)
                    .addComponent(helpbtn)
                    .addComponent(viewcolorsbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RunProgram(String FilePath)
    {
        try {
            if(SavedFile !=null && SavedFile.exists())
            {
              String command = null;
            
            if (OperatingSystem.toLowerCase().contains("windows")) {
                System.out.println("ms2molecules_win64.exe started \n");
              command = String.format("cmd /c cd "+UserDirectory+"\\bin\\windows & start cmd.exe /k ms2molecules_win64.exe %s",FilePath.trim());
             //command = String.format("cmd /c cd "+UserDirectory+"\\bin\\windows & ms2molecules_win64.exe %s",FilePath.trim());
                /*else
                { System.out.println("ms2molecules_winx86.exe started  \n");
                  command = String.format("cmd /c cd "+UserDirectory+"\\windows\\content & start cmd.exe /k ms2molecules_winx86.exe %s",FilePath.trim()); }*/
                
                Runtime.getRuntime().exec(command);
                       
		} else {
			// In case of Linux/Ubuntu run command using /bin/bash
                        command = String.format("bin/linux/ms2molecules.exe "+FilePath);
			Runtime.getRuntime().exec(new String[]{"/bin/bash", "-c", command});
		}
            }
            else
                JOptionPane.showMessageDialog(null, "First select the file to execute!");
            
        } catch (Exception ex) {
           // ex.printStackTrace();
           JOptionPane.showMessageDialog(null,"An exception occured. Please close the program and try again","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void browsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtnActionPerformed

        try{
            if(SavedFile != null && SavedFile.exists())
                                  SavedFile.delete();
            
        JFileChooser fileChooser = new JFileChooser();
        FileFilter fileFilter = new FileNameExtensionFilter("Vim Files","vim");
        fileChooser.setFileFilter(fileFilter);
        if(OpenSelectedDir != null)
                fileChooser.setCurrentDirectory(OpenSelectedDir);
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                OpenSelectedDir = selectedFile.getParentFile();
                File dest = null;
                String folderName = selectedFile.getName();//.substring(0,selectedFile.getName().length() - 4);
                Cdir = new File(UserDirectory+""+File.separator+"content"+File.separator+""+folderName);
                System.out.println(Cdir);
                /**
                 * Create folder by the name of the file in the content folder to seperate the contents
                 * from other files
                 */
                if(!Files.exists(Cdir.toPath()))
                            Cdir.mkdir();
                
                if(OperatingSystem.toLowerCase().contains("windows"))
                        dest = new File("bin\\windows\\"+selectedFile.getName());
                else
                        dest = new File("bin/linux/"+selectedFile.getName());
                
                
                Files.copy(selectedFile.toPath(), dest.toPath(),StandardCopyOption.REPLACE_EXISTING);
                SavedFile = dest;
                
                
                    
                browsetxt.setText(selectedFile.getName());
        }
        }
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"An exception occured. Please close the program and try again","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex)
         {
                JOptionPane.showMessageDialog(null,"An exception occured no IO. Please close the program and try again","Error",JOptionPane.ERROR_MESSAGE);
         }
      
    }//GEN-LAST:event_browsebtnActionPerformed

    private void runbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runbtnActionPerformed
       
        RunProgram(browsetxt.getText());
        
    }//GEN-LAST:event_runbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            if(SavedFile != null && SavedFile.exists())
                                SavedFile.delete();
            
            if(Cdir != null && Cdir.list().length <= 0 )
                Cdir.delete();
           
    }//GEN-LAST:event_formWindowClosing

    private void helpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbtnActionPerformed
        try{
         String filePath = UserDirectory+""+File.separator+"help"+File.separator+"ms2molecules_help_format.xlsx";
         Desktop.getDesktop().open(new File(filePath));
    }catch (Exception e){
      JOptionPane.showMessageDialog(null,"Exception caught ="+e.getMessage());
    }
    }//GEN-LAST:event_helpbtnActionPerformed

    private void viewcolorsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcolorsbtnActionPerformed
        try{
         String filePath = UserDirectory+""+File.separator+"help"+File.separator+"farben_neu.docx";
         Desktop.getDesktop().open(new File(filePath));
    }catch (Exception e){
      JOptionPane.showMessageDialog(null,"Exception caught ="+e.getMessage());
    }
    }//GEN-LAST:event_viewcolorsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ms2molecules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ms2molecules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ms2molecules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ms2molecules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ms2molecules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browsebtn;
    private javax.swing.JTextField browsetxt;
    private javax.swing.JButton helpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton runbtn;
    private javax.swing.JButton viewcolorsbtn;
    // End of variables declaration//GEN-END:variables
}
