/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package molecular_modeling;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.ListIterator;
import java.util.Map;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Syed Ahsan Ali
 * 
 * This class provide the functionality and Interface to add new entries to database file
 * LJ-Site:
 * Bond:
 * Angle:
 * Dihedral:
 */
public class DBEntry extends javax.swing.JFrame {

    /*
     * Creates new form DBEntry
     */
    String UserDirectory = null;
    HashMap<String,String> helpMap;
    LinkedHashMap<String,String> t_val = new LinkedHashMap<String,String>();
    molecularModeling parent = null;
    
    /**
     *
     * @param UD Path to user directory
     * @param help Help information for the UI form
     * @param context passing parent reference
     */
    public DBEntry(String UD,HashMap help,molecularModeling context) {
        initComponents();
        UserDirectory = UD;
        helpMap = help;
        BufferedImage img = null;
        parent = context;
        
        
try {
    String filepath = UserDirectory+""+File.separator+"bin"+File.separator+"images"+File.separator;
    
    img = ImageIO.read(new File(filepath+"ethan-copy2.png"));
    Image dimg = img.getScaledInstance(this.bendingimagelbl.getWidth(), this.bendingimagelbl.getHeight(),Image.SCALE_SMOOTH);
    bondimagelbl.setIcon(new ImageIcon(dimg));
    
    img = ImageIO.read(new File(filepath+"propan-copy2.png"));
    dimg = img.getScaledInstance(this.bendingimagelbl.getWidth(), this.bendingimagelbl.getHeight(),Image.SCALE_SMOOTH);
   bendingimagelbl.setIcon(new ImageIcon(dimg));
   
   img = ImageIO.read(new File(filepath+"butan-copy2.png"));
   dimg = img.getScaledInstance(this.bendingimagelbl.getWidth(), this.bendingimagelbl.getHeight(),Image.SCALE_SMOOTH);
   dihedralimagelbl.setIcon(new ImageIcon(dimg));
    
    settooltips(dbEntryTabbedPane.getComponents());
} catch (IOException e) {
    e.printStackTrace();
}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbEntryTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LJSitePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sitetypetxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sigma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        epsilon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mass = new javax.swing.JTextField();
        SaveLJsitebtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BondPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtextfield1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtextfield2 = new javax.swing.JTextField();
        jtexfield3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtextfield4 = new javax.swing.JTextField();
        SaveBondbtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        bondimagelbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BendingPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cf1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        SaveBendingbtn = new javax.swing.JButton();
        cf2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        bendingimagelbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DihedPanelT = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tor_spinner = new javax.swing.JSpinner();
        GenDihedbtn = new javax.swing.JButton();
        DihedPanelS = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        SaveDihedbtn = new javax.swing.JButton();
        dihedralimagelbl = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        statuslbl = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Site Type");

        sitetypetxt.setName("site_type"); // NOI18N
        sitetypetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });
        sitetypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitetypetxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Sigma");

        sigma.setName("sigma"); // NOI18N
        sigma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        jLabel3.setText("Epsilon");

        epsilon.setName("epsilon"); // NOI18N
        epsilon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        jLabel4.setText("Mass");

        mass.setName("mass"); // NOI18N
        mass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        SaveLJsitebtn.setText("Save");
        SaveLJsitebtn.setName("SaveLJSite"); // NOI18N
        SaveLJsitebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel22.setText("[Angström] ");

        jLabel25.setText("[K]");
        jLabel25.setToolTipText("Kelvin");

        jLabel26.setText("[u]");
        jLabel26.setToolTipText("Kelvin");

        javax.swing.GroupLayout LJSitePanelLayout = new javax.swing.GroupLayout(LJSitePanel);
        LJSitePanel.setLayout(LJSitePanelLayout);
        LJSitePanelLayout.setHorizontalGroup(
            LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LJSitePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveLJsitebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LJSitePanelLayout.createSequentialGroup()
                        .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mass)
                            .addComponent(epsilon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sigma, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitetypetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))))
                .addGap(13, 13, 13))
        );
        LJSitePanelLayout.setVerticalGroup(
            LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LJSitePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sitetypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epsilon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LJSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveLJsitebtn)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(LJSitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LJSitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        dbEntryTabbedPane.addTab("LJ-Site", jPanel1);

        jLabel5.setText("Site-i");

        jtextfield1.setName("cf1_type"); // NOI18N
        jtextfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel6.setText("Site-j");

        jtextfield2.setName("cf2_type"); // NOI18N
        jtextfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jtexfield3.setName("bond_length"); // NOI18N
        jtexfield3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        jLabel7.setText("Bond length");

        jLabel8.setText("Bond force constant");

        jtextfield4.setName("bond_constant"); // NOI18N
        jtextfield4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        SaveBondbtn.setText("Save");
        SaveBondbtn.setName("SaveBond"); // NOI18N
        SaveBondbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel23.setText("[Angström] ");

        jLabel27.setText("[K]");
        jLabel27.setToolTipText("Kelvin");

        javax.swing.GroupLayout BondPanelLayout = new javax.swing.GroupLayout(BondPanel);
        BondPanel.setLayout(BondPanelLayout);
        BondPanelLayout.setHorizontalGroup(
            BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BondPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBondbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtextfield4)
                        .addComponent(jtexfield3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtextfield2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtextfield1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BondPanelLayout.setVerticalGroup(
            BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BondPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtexfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveBondbtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        bondimagelbl.setText(".");

        jLabel20.setText("Schematic of the bond potential");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(bondimagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BondPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bondimagelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        dbEntryTabbedPane.addTab("Bonds", jPanel2);

        jLabel9.setText("Site-i");

        cf1.setName("cf2_type"); // NOI18N
        cf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel10.setText("Site-j");

        jTextField11.setName("cf3_type"); // NOI18N
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel11.setText("Site-k");

        jTextField10.setName("bending_angle"); // NOI18N
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        jLabel12.setText("Bending angle");

        jTextField9.setName("bending_constant"); // NOI18N
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoubleValFocusLost(evt);
            }
        });

        jLabel13.setText("Bending force constant");

        SaveBendingbtn.setText("Save");
        SaveBendingbtn.setName("SaveBending"); // NOI18N
        SaveBendingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBendingbtnActionPerformed(evt);
                SaveBtnActionPerformed(evt);
            }
        });

        cf2.setName("cf1_type"); // NOI18N
        cf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel24.setText("[°]");
        jLabel24.setToolTipText("This value refers to the enclosed angle by three consecutive atoms");

        jLabel28.setText("[K]");
        jLabel28.setToolTipText("Kelvin");

        javax.swing.GroupLayout BendingPanelLayout = new javax.swing.GroupLayout(BendingPanel);
        BendingPanel.setLayout(BendingPanelLayout);
        BendingPanelLayout.setHorizontalGroup(
            BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BendingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveBendingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BendingPanelLayout.createSequentialGroup()
                        .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cf1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cf2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel28))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        BendingPanelLayout.setVerticalGroup(
            BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BendingPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BendingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addComponent(SaveBendingbtn)
                .addGap(22, 22, 22))
        );

        bendingimagelbl.setText(".");

        jLabel19.setText("Schematic of the angle potential");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(bendingimagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BendingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bendingimagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        dbEntryTabbedPane.addTab("Angle", jPanel3);

        DihedPanelT.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(DihedPanelT);

        jLabel18.setText("Number of dihedral force constant");

        tor_spinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        GenDihedbtn.setText("Generate");
        GenDihedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenDihedbtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Site-i");

        jTextField17.setName("cf1_type"); // NOI18N
        jTextField17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel15.setText("Site-j");

        jTextField16.setName("cf2_type"); // NOI18N
        jTextField16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel16.setText("Site-k");

        jTextField15.setName("cf3_type"); // NOI18N
        jTextField15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        jLabel17.setText("Site-l");

        jTextField14.setName("cf4_type"); // NOI18N
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sitetypetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SiteTypesFocusLost(evt);
            }
        });

        SaveDihedbtn.setText("Save");
        SaveDihedbtn.setName("SaveDihed"); // NOI18N
        SaveDihedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DihedPanelSLayout = new javax.swing.GroupLayout(DihedPanelS);
        DihedPanelS.setLayout(DihedPanelSLayout);
        DihedPanelSLayout.setHorizontalGroup(
            DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DihedPanelSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveDihedbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField14)
                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DihedPanelSLayout.setVerticalGroup(
            DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DihedPanelSLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DihedPanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(SaveDihedbtn)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        dihedralimagelbl.setText(".");

        jLabel21.setText("Schematic of the dihedral potential");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DihedPanelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tor_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(234, 234, 234))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenDihedbtn)
                            .addComponent(dihedralimagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DihedPanelS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tor_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenDihedbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(dihedralimagelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dbEntryTabbedPane.addTab("Dihedral", jPanel4);

        statuslbl.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuslbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dbEntryTabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dbEntryTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statuslbl)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Get all the label and buttons from the UI 
     * assign tool tip from the populated hashMap (helpmap) 
     * call addlinebreaks function to make tool tip in paragraph form 
     * use html tags inside tool tip to formate paragrah form.
     * 
     * @param component UI controls
     * 
     */
    private void settooltips(Component[] component)
    {
        for(Component cm: component)
        {
            if(cm instanceof JLabel)
            {
                JLabel lbl = (JLabel) cm;
                String tooltip = addLinebreaks(helpMap.get(lbl.getText().toLowerCase().trim()),30);
                lbl.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
            }
            else
            if(cm instanceof JButton)
            {
                JButton btn = (JButton) cm;
                String tooltip = addLinebreaks(helpMap.get(btn.getText().toLowerCase().trim()),30);
                btn.setToolTipText("<html><body><p>"+tooltip+"</p></body></html>");
            }
            else
                if(cm instanceof JPanel)
                {
                    JPanel innerPanel = (JPanel) cm;
                    settooltips(innerPanel.getComponents());
                }
        }
    }


    /**
     *
     * To add line breaks after every specified characters length
     * Input: String which needed to be break in line 
     * maxLineLength: maximum length specified to break the line
     * 
     * @param input String for help
     * @param maxLineLength Maximum length of a line
     * 
     * @return Formatted string
     */
    
     public String addLinebreaks(String input, int maxLineLength) {
    if(input != null)
    {
    StringTokenizer tok = new StringTokenizer(input, " ");
    StringBuilder output = new StringBuilder(input.length());
    int lineLen = 0;
    while (tok.hasMoreTokens()) {
        String word = tok.nextToken();

        if (lineLen + word.length() > maxLineLength) {
            output.append("<br>");
            lineLen = 0;
        }
        output.append(word+" ");
        lineLen += word.length();
    }
    return output.toString();
    }
    
    return "";
}
     
     /**
     *
     * This function get all the components (Textboxes) form the Jpanel from 
     * where the user pressed the specified saved button. And stores all the 
     * values to the hashmap (t_val) provided by the user.
     * 
     * @param panel Panel to get UI controls to save data
     * 
     * @return True - False
     */
    private boolean getComponents(JPanel panel)
    {
        t_val.clear();
        Component[] cmp = panel.getComponents();
        System.out.println(cmp.length);
        if(cmp.length > 0)
        {
        for(Component c: cmp)
        {
            if(c instanceof JTextField)
            {
                JTextField tField = (JTextField) c;
                System.out.println(tField.getText()+"\n");
                System.out.println(tField.getName()+"\n");
                if(tField.getName().equals("bond_constant") && (tField.getText() == null || tField.getText().equals("")))
                                   continue;
                
                if(tField.getText() != null && !tField.getText().equals(""))
                {
                    t_val.put(tField.getName(), tField.getText());
                }
                else
                {
                    this.setAlwaysOnTop(false);
                   JOptionPane.showMessageDialog(null,"Not all Sites are defined");
                    statuslbl.setText("error occurred.");
                    this.setAlwaysOnTop(true);
                    return false;
                }
            }
        }
        }
        else{
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null,"There are 0 number of torsion & gemma");
            statuslbl.setText("error occurred.");
            this.setAlwaysOnTop(true);
            return false;
        }
        
         System.out.println("got all components\n");
         return true;
    }
    /*
        .
    */
    
    /**
     *
     * @see DBEntry#SaveBtnActionPerformed(java.awt.event.ActionEvent)
     * 
     * This function then formates all the provided values for hashmap 
     * (t_val) in to the specified database formate and write these 
     * formated values to the database file.
     * 
     * @param segment Segment Which to save data
     * 
     */
    private void writeTypesinDB(String segment)
    {
        String filepath = UserDirectory+""+File.separator+"Database"+File.separator+"potparam.txt";
        FileInputStream in = null;
        Scanner sc = null;
        BufferedWriter wr = null;
        try {
            
        in = new FileInputStream(filepath);
        sc = new Scanner(in,"UTF-8");
        StringBuffer content = new StringBuffer();
        String line = null;
        while(sc.hasNextLine()){
            line = sc.nextLine();
            content.append(line+"\n");
            
            if(line.contains(segment))
                               break;
                    }
        
        while(sc.hasNextLine())
        {
            line = sc.nextLine();
            content.append(line+"\n");
            
        if(line.contains("/"))
                    break; 
        }
        
        //ListIterator iterate =  (ListIterator) (types.entrySet()).iterator();
        ListIterator<Map.Entry<String, String>> iterator = new ArrayList<Map.Entry<String, String>>(t_val.entrySet()).listIterator(t_val.size());
        content.append("\n"+segment+"\n");
        
        while(iterator.hasPrevious())
        {
            Map.Entry entry = (Map.Entry) iterator.previous();
            //line = "   "+entry.getKey()+"\t= "+entry.getValue();
            line = String.format("   %-17s= %s", entry.getKey(),entry.getValue());
            content.append(line+"\n");
        }
        
        if(segment.equals("&torsion"))
        {
           if(getComponents(DihedPanelT))
           {
            Iterator itr =  t_val.entrySet().iterator();
            while(itr.hasNext())
            {
                Map.Entry entry = (Map.Entry) itr.next();
               // line = "   "+entry.getKey()+"\t= "+entry.getValue();
                line = String.format("   %-17s= %s", entry.getKey(),entry.getValue());
                content.append(line+"\n");
            }
           }
        }
        
            line = "/\n";
            content.append(line+"\n");
            
        while(sc.hasNextLine())
        {
            line = sc.nextLine();
            content.append(line+"\n");
        }
        
        
        wr = new BufferedWriter(new FileWriter(filepath));
                   wr.append(content);

        System.out.println("all done!\n");
        segment = segment.substring(1);
        statuslbl.setText(segment+" entry saved successfully!");
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DBEntry.class.getName()).log(Level.SEVERE, null, ex);
            statuslbl.setText("An exception occurred. Try again");
        }
        catch (Exception ex)
        {
            Logger.getLogger(DBEntry.class.getName()).log(Level.SEVERE, null, ex);
            statuslbl.setText("An exception occurred. Try again");
        }
        finally{ 
            try {
                    if (in != null) {
                            in.close();
                }
                    if (sc != null) {
                        sc.close();
                    }
                 if (wr != null) {
                        wr.close();
                    }
            } catch (IOException ex) {
                Logger.getLogger(DBEntry.class.getName()).log(Level.SEVERE, null, ex);
                statuslbl.setText("An exception occurred. Try again");
            }
        }
    }
    
    /**
     * 
     * After saving, clear all the textboxes for the next entry.
     * 
    */
    private void clearall()
    {
        DihedPanelT.removeAll();
        
        for(Component c: dbEntryTabbedPane.getComponents())
        {
            if(c instanceof JPanel)
            {
                JPanel outp = (JPanel) c;
                for(Component cp: outp.getComponents())
                {
                    if(cp instanceof JPanel)
                    {
                        JPanel inp = (JPanel) cp;
                        for(Component ct: inp.getComponents())
                        {
                            if(ct instanceof JTextField)
                            {
                                JTextField jt = (JTextField) ct;
                                jt.setText("");
                            }
                        }
                    }
                }
            }
        }
    }
    
   /**
    * Save button event handler
    * 
    */
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        
            JButton saveB = (JButton) evt.getSource();
        
            if(saveB.getName().equals("SaveLJSite"))
            {
                try {
                    if(site_type_exists())
                        if(getComponents(LJSitePanel))
                            writeTypesinDB("&site");
                } catch (IOException ex) {
                    Logger.getLogger(DBEntry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            if(saveB.getName().equals("SaveBond"))
            {
                if(getComponents(BondPanel))
                         writeTypesinDB("&bond");
            }
            else
            if(saveB.getName().equals("SaveBending"))
            {
                if(getComponents(BendingPanel))
                        writeTypesinDB("&bending");
            }
            else
            if(saveB.getName().equals("SaveDihed"))
            {
                if(getComponents(DihedPanelS))
                        writeTypesinDB("&torsion");
            }
            
            clearall();
    }//GEN-LAST:event_SaveBtnActionPerformed
    
    /**
     * This function is to check if there is any entry provided by
     * the user already exists or not.
     * 
     * @return True - False
    */
    private boolean site_type_exists() throws IOException
    {
        BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader(UserDirectory+""+File.separator+"Database"+File.separator+"potparam.txt"));
            while(in.ready())
            {
                String line = in.readLine().trim();
                if(line.startsWith("site_type"))
                {
                   String[] DBn = line.split("=");
                   DBn[1] = DBn[1].replace("\\par", "").trim();
                  // System.out.println(">>> 1st : "+DBn[1]);
                  // System.out.println(">>> 2nd : "+sitetypetxt.getText());
                   if(sitetypetxt.getText().trim().equalsIgnoreCase(DBn[1]))
                   {
                       this.setAlwaysOnTop(false);
                       JOptionPane.showMessageDialog(null,"Site_Type already exists");
                       this.setAlwaysOnTop(true);
                       return false;
                   }
                   
               
            }
             if(line.startsWith("&bond"))
                            break;
            }
            
            
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
            statuslbl.setText("An exception occured database file not found");
            return false;
           // log.append("!!! Caught Exception while reading Database types\n");
        }
        catch(IOException ex)
        {
            statuslbl.setText("An exception occured could'nt read database file");
            return false;
        }
        catch(Exception ex)
        {
            statuslbl.setText("An exception occured please try again");
            return false;
        }
        finally{
            if(in != null)
                    in.close();
        }
        
        return true;
    }
    private void SaveBendingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBendingbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBendingbtnActionPerformed
    
    /**
     * 
     * Focus lost event handler for all the "type" textboxes to add " ' " to the type values.
     * 
    */
    private void SiteTypesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SiteTypesFocusLost
        JTextField sf = (JTextField) evt.getSource();
        if(sf.getText() != null && !sf.getText().equals(""))
        {
            if(!sf.getText().startsWith("'"))
                         sf.setText("'"+sf.getText());
            
            if(!sf.getText().endsWith("'"))
                sf.setText(sf.getText()+"'");
        }
                                    
        
    }//GEN-LAST:event_SiteTypesFocusLost
   
    /**
     * 
     * Event handler for the "Generate" button in dihedral to generate all 
     * the labels and textboxes for the specified number of value from the user.
     * 
    */
    private void GenDihedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenDihedbtnActionPerformed
                        DihedPanelT.removeAll();
                        
        int num = Integer.parseInt(tor_spinner.getValue().toString()) * 2;
      //  ArrayList<JTextField> jt = new ArrayList<JTextField>();
        
        System.out.println(num);
                        GridBagConstraints textFieldConstraints = new GridBagConstraints();
                        textFieldConstraints.fill = GridBagConstraints.VERTICAL;
                        textFieldConstraints.weightx = 0;
                        textFieldConstraints.weighty = 0;
                        textFieldConstraints.insets = new Insets(10, 10, 10, 10);
                        
                        for(int i=0, j = 0 ; i < num; i += 2,j++)
                         {
                             // set grid(position) for the label 
                                textFieldConstraints.gridx = 0;
                                textFieldConstraints.gridy = i;

                                JLabel gl = new JLabel("Gamma_"+j);
                                DihedPanelT.add(gl,textFieldConstraints);
                                
                                // set grid for the associated textbox
                                textFieldConstraints.gridx++;
                                JTextField gf=new JTextField("0.0");
                                gf.setName("gamma_c"+String.valueOf(j));
                                gf.setPreferredSize(new Dimension(160,26));
                                gf.addFocusListener(new FocusListener(){
                                   @Override public void focusLost(FocusEvent evt) { DoubleValFocusLost(evt); }
                                   @Override public void focusGained(final FocusEvent pE) {}
                                });
                                DihedPanelT.add(gf,textFieldConstraints);
                                
                                //set grid for gemma unit label
                                textFieldConstraints.gridx++;
                                JLabel gu = new JLabel("[°]");
                                DihedPanelT.add(gu,textFieldConstraints);

                                textFieldConstraints.gridx = 0;
                                textFieldConstraints.gridy = i+1;

                                JLabel tl = new JLabel("Torsion_"+j);
                                DihedPanelT.add(tl,textFieldConstraints);

                                textFieldConstraints.gridx++;

                                JTextField tf=new JTextField("0.0");
                                tf.setName("torsion_c"+String.valueOf(j));
                                tf.setPreferredSize(new Dimension(160,26));
                                tf.addFocusListener(new FocusListener(){
                                   @Override public void focusLost(FocusEvent evt) {DoubleValFocusLost(evt);}
                                    @Override public void focusGained(final FocusEvent pE) {}
                                });
                                DihedPanelT.add(tf,textFieldConstraints);
                                
                                //set grid for the unit label
                                textFieldConstraints.gridx++;
                                JLabel tu = new JLabel("[K]");
                                DihedPanelT.add(tu,textFieldConstraints);
                        
                         }
        
       DihedPanelT.revalidate();
    }//GEN-LAST:event_GenDihedbtnActionPerformed

    private void sitetypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitetypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitetypetxtActionPerformed
    
    /**
     * 
     * validate the double values when user move to the next control.
     * 
    */
    private void DoubleValFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoubleValFocusLost
        JTextField sf = (JTextField) evt.getSource();
        try{
            
            if(sf.getText() != null && !sf.getText().equalsIgnoreCase(""))
            {
                          double d =  Double.parseDouble(sf.getText());
                      if(Double.compare(d, 0.0) < 0.0)
                          {
                              this.setAlwaysOnTop(false);
                              JOptionPane.showMessageDialog(null, "Value can not be negative");
                              this.setAlwaysOnTop(true);
                              sf.requestFocus();
                              sf.selectAll();
                          }
            }
        }
        catch(Exception ex)
        {
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null, "Only number values are allowed/wrong seperator between number values");
            this.setAlwaysOnTop(true);
            sf.requestFocus();
            sf.selectAll();
        }
    }//GEN-LAST:event_DoubleValFocusLost
    
    /**
     * 
     * event handler to handle " ' " for the type values.
     * 
    */
    private void sitetypetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sitetypetxtFocusGained
        JTextField sf = (JTextField) evt.getSource();
        if(sf.getText() != null && !sf.getText().equals(""))
        {
            if(sf.getText().startsWith("'"))
                         sf.setText(sf.getText().substring(1));
            
            if(sf.getText().endsWith("'"))
                sf.setText(sf.getText().substring(0, sf.getText().length() - 1));
        }
    }//GEN-LAST:event_sitetypetxtFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new DBEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BendingPanel;
    private javax.swing.JPanel BondPanel;
    private javax.swing.JPanel DihedPanelS;
    private javax.swing.JPanel DihedPanelT;
    private javax.swing.JButton GenDihedbtn;
    private javax.swing.JPanel LJSitePanel;
    private javax.swing.JButton SaveBendingbtn;
    private javax.swing.JButton SaveBondbtn;
    private javax.swing.JButton SaveDihedbtn;
    private javax.swing.JButton SaveLJsitebtn;
    private javax.swing.JLabel bendingimagelbl;
    private javax.swing.JLabel bondimagelbl;
    private javax.swing.JTextField cf1;
    private javax.swing.JTextField cf2;
    private javax.swing.JTabbedPane dbEntryTabbedPane;
    private javax.swing.JLabel dihedralimagelbl;
    private javax.swing.JTextField epsilon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jtexfield3;
    private javax.swing.JTextField jtextfield1;
    private javax.swing.JTextField jtextfield2;
    private javax.swing.JTextField jtextfield4;
    private javax.swing.JTextField mass;
    private javax.swing.JTextField sigma;
    private javax.swing.JTextField sitetypetxt;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JSpinner tor_spinner;
    // End of variables declaration//GEN-END:variables
}
