/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package molecular_modeling;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Syed Ahsan Ali
 * 
 *This class provide the logic and interface for the LJ-Site
 *  additional parameters for .par files
 */
public class LJSites extends javax.swing.JFrame {

    /**;
     * 
     * Creates new form LJSites
     */
    EachRowEditor rowEditor;
    List<JComboBox> Jbox = new ArrayList<JComboBox>();
    ArrayList<String> ljtype = new ArrayList<String>();
    int[] len;
    molecularModeling parent = null;
    final LJSites thisClass = this;
    /**
     *
     */
    public LJSites() {
        initComponents();
        addtablellistner();
        try {
            rowEditor = new EachRowEditor(ljtypetable);
            ljtypetable.getColumn("LJType").setCellEditor(rowEditor);
        } catch (Exception ex) {
            System.out.println(ex.getStackTrace());
        }
    }
    
    private void addtablellistner() {
        ljtypetable.getModel().addTableModelListener(new TableModelListener(){
            
            @Override
            public void tableChanged(TableModelEvent e) {
                
                int col = e.getColumn();
                int row = ljtypetable.getSelectedRow();
              //  JOptionPane.showMessageDialog(null,row + "-" + col);
                switch (e.getType()) {

                    case TableModelEvent.UPDATE:
                        if(row > -1) {
                        
                            if(col == 2) {
                                if(ljtypetable.getValueAt(row, 2).toString().equals("benzene") && len[row] > 1){
                                    thisClass.setAlwaysOnTop(false);
                                    JOptionPane.showMessageDialog(null, "On id "+ row +": Benzene can be added in the middle", "Benzene Warning", JOptionPane.WARNING_MESSAGE);
                                    thisClass.setAlwaysOnTop(true);
                                    ljtypetable.setValueAt("", row, col);
                                }
                                if(ljtypetable.getValueAt(row, 2).toString().equals("OH") && len[row] > 2){
                                    thisClass.setAlwaysOnTop(false);
                                    JOptionPane.showMessageDialog(null,"On id "+ row +": OH can not be added after 3 connections", "OH Warning", JOptionPane.WARNING_MESSAGE);
                                    thisClass.setAlwaysOnTop(true);
                                    ljtypetable.setValueAt("", row, col);
                                }
                            }
                            
                        }
                        
                    break;
                }
            }
        });
    }
    /**
     * 
     * Add dropdown with values inside the provided table
     * where user can select specified values 
     * And save dropdown object to dropdown arraylist for reusing 
     * or updating the dropdown.
     * 
     * @see molecularModeling#ljsitebtnActionPerformed(java.awt.event.ActionEvent)
     * 
     * @param content
     * 
     */
    
    public void GenerateLJTypeTable(String[][] content,molecularModeling context)
    {
        parent = context;
        len = new int[content.length];
        DefaultTableModel tm = (DefaultTableModel) ljtypetable.getModel();
        String[] types = {"","OH","charge","benzene"};
        for(int i = tm.getRowCount(); i < content.length; i++)
            {
                tm.addRow(new Object[]{content[i][0],content[i][1]});
                JComboBox jm = new JComboBox(types);
                Jbox.add(jm);
                rowEditor.setEditorAt(i, new DefaultCellEditor(Jbox.get(Jbox.size() - 1)));
                len[i] = Integer.parseInt(content[i][2]);
            }
    }
    
    /**
     * Checks if LJtyoe exist or not.
     * 
     * @return LJtype or null
     */
    public ArrayList<String> GetLJType()
    {
        if(ljtype.size() > 0)
                return ljtype;
        else
            return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ljtypetable = new javax.swing.JTable();
        savebtn = new javax.swing.JButton();

        setAlwaysOnTop(true);

        ljtypetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Database", "LJType"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ljtypetable);

        jScrollPane1.setViewportView(jScrollPane2);

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * eventhandler for the save button to save all the provided values by the users
     * And save values to the "ljtype" arraylist.
     * 
    */
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        ljtype.clear();
        for(int i=0; i<ljtypetable.getRowCount();i++)
        {
            
            if(ljtypetable.getValueAt(i, 2) != null && !ljtypetable.getValueAt(i, 2).toString().isEmpty())
            {
                 ljtype.add(i+"-"+ljtypetable.getValueAt(i, 2).toString());
                //System.out.println(i+"-"+ljtypetable.getValueAt(i, 2).toString());
                //break;
                
            }
        }
        
        System.out.println(ljtype.size());
        this.setVisible(false);
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LJSites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LJSites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LJSites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LJSites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LJSites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ljtypetable;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
